### PR TITLE
Problem (Fix #1485): mock-utils may crash when the payload is less than 16 bytes

### LINKED ISSUE #1485: Problem: mock-utils may crash when the payload is less than 16 bytes
A new crash was discovered for fuzzing target abci-cycle.
Here is a snippet of the log:
```
e::_$u7b$$u7b$closure$u7d$$u7d$::hc7bcff1af2972577 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/src/lib.rs:51:9
FUZZER:     #11 0x5625066600a4 in std::panicking::rust_panic_with_hook::h5035e60b675c5c99 /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/panicking.rs:515:17
FUZZER:     #12 0x56250665fbba in rust_begin_unwind /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/panicking.rs:419:5
FUZZER:     #13 0x562506695220 in core::panicking::panic_fmt::h7fe09dc6d8aa54c4 /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libcore/panicking.rs:111:14
FUZZER:     #14 0x56250669516c in core::panicking::panic::h37e73c92ba5667a9 /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libcore/panicking.rs:54:5
FUZZER:     #15 0x562501770982 in mock_utils::unpad_payload::h6dfd658d6f5dbf54 /drone/src/chain-tx-enclave/mock-utils/src/lib.rs:16:17
FUZZER:     #16 0x562501770287 in mock_utils::decrypt::hd1854ad07bad2614 /drone/src/chain-tx-enclave/mock-utils/src/lib.rs:10:17
FUZZER:     #17 0x56250148bda9 in _$LT$chain_abci..enclave_bridge..mock..MockClient$u20$as$u20$chain_abci..enclave_bridge..EnclaveProxy$GT$::process_request::hd067bd78c77fd109 /drone/src/chain-abci/src/enclave_bridge/mock.rs:92:32
FUZZER:     #18 0x562500d16f90 in chain_abci::storage::verify_enclave_tx::had3edbe2fa5702ed /drone/src/chain-abci/src/storage/mod.rs:249:28
FUZZER:     #19 0x562500c7ce08 in chain_abci::app::validate_tx::_$LT$impl$u20$chain_abci..app..app_init..ChainNodeApp$LT$T$GT$$GT$::process_tx::hd847384f4494bc57 /drone/src/chain-abci/src/app/validate_tx.rs:76:30
FUZZER:     #20 0x562500c9ede9 in chain_abci::app::_$LT$impl$u20$abci..Application$u20$for$u20$chain_abci..app..app_init..ChainNodeApp$LT$T$GT$$GT$::check_tx::h10281d2b1482db0d /drone/src/chain-abci/src/app/mod.rs:75:15
FUZZER:     #21 0x562500d0c612 in rust_fuzzer_test_input /drone/src/chain-abci/fuzz/fuzz_targets/abci_cycle.rs:213:25
FUZZER:     #22 0x56250106af72 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::hfa0dcb95cd4d9a5a /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/src/lib.rs:27:9
FUZZER:     #23 0x5625010c14f4 in std::panicking::try::do_call::h101d7ca0873adaa1 /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/panicking.rs:331:40
FUZZER:     #24 0x5625010c199a in __rust_try (/app/fuzzer+0x1f9899a)
FUZZER:     #25 0x5625010c108e in std::panicking::try::h4e202cb25119c7dd /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/panicking.rs:274:15
FUZZER:     #26 0x5625010c07bc in std::panic::catch_unwind::h578fe8ee56290d39 /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/panic.rs:394:14
FUZZER:     #27 0x56250106a8b9 in LLVMFuzzerTestOneInput /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/src/lib.rs:25:22
FUZZER:     #28 0x5625010848fd in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:553
FUZZER:     #29 0x562501084180 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:469
FUZZER:     #30 0x562501085a85 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:766
FUZZER:     #31 0x562501085d1c in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:793
FUZZER:     #32 0x5625010723d3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerDriver.cpp:825
FUZZER:     #33 0x56250106a5bd in main /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerMain.cpp:19
FUZZER:     #34 0x7faff136f2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
FUZZER:     #35 0x562500b30389 in _start (/app/fuzzer+0x1a07389)
FUZZER: 
FUZZER: NOTE: libFuzzer has rudimentary signal handlers.
FUZZER:       Combine libFuzzer with AddressSanitizer or similar for better crash reports.
FUZZER: SUMMARY: libFuzzer: deadly signal
FUZZER: MS: 0 ; base unit: 0000000000000000000000000000000000000000
FUZZER: artifact_prefix='./'; Test unit written to ./artifact
FUZZER: stat::number_of_executed_units: 3679
FUZZER: stat::average_exec_per_sec:     60
FUZZER: stat::new_units_added:          0
FUZZER: stat::slowest_unit_time_sec:    0
FUZZER: stat::peak_rss_mb:              533
2020/04/24 06:24:47 process finished with error = exit status 76
2020/04/24 06:24:47 Exit Status: 76
2020/04/24 06:24:47 uploading crash...

```

More details can be found [here](https://app.fuzzit.dev/orgs/crypto-com-gh/targets/abci-cycle/pTbq94OrLj2Y0UJdaoF4)

Cheers,
Fuzzit Bot

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Change the return value of unpad_payload to Result

### CODE REVIEW

File: chain-tx-enclave/mock-utils/src/lib.rs [hunk 1]
```diff
@@ -7,13 +7,17 @@ use chain_tx_validation::Error;
...
-    let unpad = unpad_payload(&payload.txpayload);
+    let unpad = unpad_payload(&payload.txpayload)?;
     let bs = unpad.iter().map(|b| b ^ ENCRYPTION_KEY).collect::<Vec<_>>();
     PlainTxAux::decode(&mut bs.as_slice()).map_err(|_| Error::EnclaveRejected)
 }
 
-fn unpad_payload(payload: &[u8]) -> &[u8] {
-    &payload[0..payload.len() - 16]
+fn unpad_payload(payload: &[u8]) -> Result<&[u8], Error> {
+    if let Some(n) = payload.len().checked_sub(16) {
```
Comment (leejw51crypto) [inline chain-tx-enclave/mock-utils/src/lib.rs:16]: wondering whether
0.. payload.len()- (payload.len()%16) 
For unpadding?
