### PR TITLE
Problem: (fix #1413) Milli::new and Milli:: integral may overflow

### LINKED ISSUE #1413: Problem: Milli::new and Milli:: integral may overflow
A new crash was discovered for fuzzing target abci-cycle.
Here is a snippet of the log:
```
8cf131a1f in _$LT$core..marker..PhantomData$LT$T$GT$$u20$as$u20$serde..de..DeserializeSeed$GT$::deserialize::hca907e790d224de2 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.105/src/de/mod.rs:786:8
FUZZER:     #35 0x5598cef359cc in _$LT$serde_json..de..MapAccess$LT$R$GT$$u20$as$u20$serde..de..MapAccess$GT$::next_value_seed::haa33db0b9a449b48 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.48/src/de.rs:1794:8
FUZZER:     #36 0x5598cef179ff in serde::de::MapAccess::next_value::h6c14e83f447960fb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.105/src/de/mod.rs:1847:8
FUZZER:     #37 0x5598cf05eda7 in _$LT$chain_core..init..config.._IMPL_DESERIALIZE_FOR_InitConfig..$LT$impl$u20$serde..de..Deserialize$u20$for$u20$chain_core..init..config..InitConfig$GT$..deserialize..__Visitor$u20$as$u20$serde..de..Visitor$GT$::visit_map::ha50066ee4f27e37d /drone/src/chain-core/src/init/config.rs:76:60
FUZZER:     #38 0x5598cef930a3 in _$LT$$RF$mut$u20$serde_json..de..Deserializer$LT$R$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_struct::h391b6c4638eaab24 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.48/src/de.rs:1621:30
FUZZER:     #39 0x5598cf05d76c in chain_core::init::config::_IMPL_DESERIALIZE_FOR_InitConfig::_$LT$impl$u20$serde..de..Deserialize$u20$for$u20$chain_core..init..config..InitConfig$GT$::deserialize::ha9c06c58471b7b46 /drone/src/chain-core/src/init/config.rs:76:60
FUZZER:     #40 0x5598ceef4fdd in serde_json::de::from_trait::h57acbeb14552ff01 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.48/src/de.rs:2177:21
FUZZER:     #41 0x5598ceef4ae2 in serde_json::de::from_slice::h547761bdcbcb9ce0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.48/src/de.rs:2335:4
FUZZER:     #42 0x5598cee58846 in rust_fuzzer_test_input /drone/src/chain-abci/fuzz/fuzz_targets/abci_cycle.rs:106:24
FUZZER:     #43 0x5598cf1af122 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::h6630f278e6de5bc0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/src/lib.rs:27:8
FUZZER:     #44 0x5598cf2053f4 in std::panicking::try::do_call::h5fad5868ec171aee /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:303:39
FUZZER:     #45 0x5598d40d4cc6 in __rust_maybe_catch_panic /rustc/834bc5650acf7019a53b409db68986857822812c/src/libpanic_unwind/lib.rs:86:7
FUZZER:     #46 0x5598cf204de5 in std::panicking::try::h7880546378c8b6a4 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:281:12
FUZZER:     #47 0x5598cf203fbc in std::panic::catch_unwind::ha9e3255c77111d25 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panic.rs:394:13
FUZZER:     #48 0x5598cf1aea69 in LLVMFuzzerTestOneInput /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/src/lib.rs:25:21
FUZZER:     #49 0x5598cf1c8b07 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:553
FUZZER:     #50 0x5598cf1c838a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:469
FUZZER:     #51 0x5598cf1c95fa in fuzzer::Fuzzer::MutateAndTestOne() /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:696
FUZZER:     #52 0x5598cf1ca1e1 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerLoop.cpp:831
FUZZER:     #53 0x5598cf1b65dd in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerDriver.cpp:825
FUZZER:     #54 0x5598cf1ae76d in main /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.2/libfuzzer/FuzzerMain.cpp:19
FUZZER:     #55 0x7eff7e9cb2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
FUZZER:     #56 0x5598ced8f409 in _start (/app/fuzzer+0x17e0409)
FUZZER: 
FUZZER: NOTE: libFuzzer has rudimentary signal handlers.
FUZZER:       Combine libFuzzer with AddressSanitizer or similar for better crash reports.
FUZZER: SUMMARY: libFuzzer: deadly signal
FUZZER: MS: 1 CopyPart-; base unit: 35bab406ecd490ed12266ed1e91934e89cb6fd83
FUZZER: artifact_prefix='./'; Test unit written to ./artifact
FUZZER: stat::number_of_executed_units: 95517
FUZZER: stat::average_exec_per_sec:     49
FUZZER: stat::new_units_added:          32
FUZZER: stat::slowest_unit_time_sec:    0
FUZZER: stat::peak_rss_mb:              497
2020/03/27 19:29:45 process finished with error = exit status 76
2020/03/27 19:29:45 Exit Status: 76
2020/03/27 19:29:46 uploading crash...

```

More details can be found [here](https://app.fuzzit.dev/orgs/crypto-com-gh/targets/abci-cycle/Ke6rz20qVKzYw6ZkK7pO)

Cheers,
Fuzzit Bot

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution:
* add a `try_new` function, when overflow, return Error.

### CODE REVIEW

File: chain-core/src/tx/fee/mod.rs [hunk 1]
```diff
@@ -45,10 +45,27 @@ impl Milli {
     /// takes the integer part and 3-digit fractional part
     /// and returns the 3-digit fixed decimal number (i.fff)
     #[inline]
-    pub const fn new(i: u64, f: u64) -> Self {
+    pub(crate) const fn new(i: u64, f: u64) -> Self {
```
Comment (devashishdxt) [inline chain-core/src/tx/fee/mod.rs:48]: Can we remove this function?

Comment (linfeng-crypto) [reply chain-core/src/tx/fee/mod.rs:48]: because of the code [`const MAX_SLASH_RATIO: Milli = Milli::new(1, 0);`](https://github.com/crypto-com/chain/blob/master/chain-core/src/init/params.rs#L13), we need a const function, but we can not set the `try_new` function as const, if remove the `const fn new()`, we need `lazy_static` or `once_cell` to set the const value.

**Comment by linfeng-crypto** [comment]
> serde deserialization

I add a deserd test and found out that when the number is larger than u64::MAX, it will be a type error:

```
Err(Error("invalid type: floating point `18446744073709552000`, expected u64", line: 1, column: 28))

```
the number is `18446744073709551616` which is equal to` u64::MAX+1`, and it does not crush, just gives an error, trades `u64::MAX+1` as a float number.

File: chain-abci/benches/tx.rs [hunk 2]
```diff
@@ -86,7 +86,10 @@ fn init_chain_for(addresses: &Vec<RedeemAddress>) -> ChainNodeApp {
     );
 
     let params = InitNetworkParameters {
-        initial_fee_policy: LinearFee::new(Milli::new(1, 1), Milli::new(1, 1)),
+        initial_fee_policy: LinearFee::new(
+            Milli::try_new(1, 1).unwrap(),
```
Comment (leejw51crypto) [inline chain-abci/benches/tx.rs:90]: expect?

File: chain-core/src/init/params.rs [hunk 3]
```diff
@@ -197,7 +197,7 @@ impl RewardsParameters {
     /// check if reward parameters are correct
     /// TODO: hide values and check these in `new` + deserialize/decode?
     pub fn validate(&self) -> Result<(), &'static str> {
-        if self.monetary_expansion_r0 > Milli::integral(1) {
+        if self.monetary_expansion_r0 > Milli::integral(1).map_err(|_| "overflow")? {
```
Comment (leejw51crypto) [inline chain-core/src/init/params.rs:200]: Milli integral overflow?

File: chain-core/src/tx/fee/mod.rs [hunk 4]
```diff
@@ -96,6 +106,8 @@ pub enum MilliError {
     InvalidPartsLength(usize),
     /// Number parsing error
     InvalidInteger(ParseIntError),
+    /// too large to overflow
+    Overflow,
```
Comment (leejw51crypto) [inline chain-core/src/tx/fee/mod.rs:110]: longer word, for ease of coding

IntegralOverflow

File: test-common/src/chain_env.rs [hunk 5]
```diff
@@ -85,7 +85,10 @@ pub fn create_storage() -> Storage {
 
 pub fn get_init_network_params(expansion_cap: Coin) -> InitNetworkParameters {
     InitNetworkParameters {
-        initial_fee_policy: LinearFee::new(Milli::new(0, 0), Milli::new(0, 0)),
+        initial_fee_policy: LinearFee::new(
+            Milli::try_new(0, 0).unwrap(),
```
Comment (leejw51crypto) [inline test-common/src/chain_env.rs:89]: expect?

Comment (linfeng-crypto) [reply test-common/src/chain_env.rs:89]: Ok

**Comment by linfeng-crypto** [comment]
some unit tests failed, I'm checking.

File: chain-abci/benches/tx.rs (hunk 2 above)
Comment (linfeng-crypto) [reply chain-abci/benches/tx.rs:90]: it is the beche for testing, and it will never fail I think, so it doesn't matter to use unwrap.

File: chain-core/src/init/params.rs [hunk 6]
```diff
@@ -197,7 +197,7 @@ impl RewardsParameters {
     /// check if reward parameters are correct
     /// TODO: hide values and check these in `new` + deserialize/decode?
     pub fn validate(&self) -> Result<(), &'static str> {
-        if self.monetary_expansion_r0 > Milli::integral(1) {
+        if self.monetary_expansion_r0 > Milli::integral(1).map_err(|_| "milli integral overflow")? {
```
Comment (tomtau) [inline chain-core/src/init/params.rs:200]: this one is a constant, so unwrap/expect may be fine
