### PR TITLE
Problem: broken nightly compilation due to FFI pass-by-value array in cro-clib (fix #1826)

### LINKED ISSUE #1826: Problem: broken nightly compilation due to FFI pass-by-value array in cro-clib
https://github.com/crypto-com/chain/pull/1795#issuecomment-649959728
```
error: `extern` fn uses type `[u8; 32]`, which is not FFI-safe
874   --> cro-clib/src/transaction_build.rs:109:11
875    |
876109 |     txid: [u8; 32],
877    |           ^^^^^^^^ not FFI-safe
878    |
879    = note: `-D improper-ctypes-definitions` implied by `-D warnings`
880    = help: consider passing a pointer to the array
881    = note: passing raw arrays by value is not FFI-safe
882
883error: `extern` fn uses type `[u8; 32]`, which is not FFI-safe
884   --> cro-clib/src/transaction_build.rs:111:11
885    |
886111 |     addr: [u8; 32],
887    |           ^^^^^^^^ not FFI-safe
888    |
889    = help: consider passing a pointer to the array
890    = note: passing raw arrays by value is not FFI-safe
891
892error: `extern` fn uses type `[u8; 33]`, which is not FFI-safe
893   --> cro-clib/src/transaction_build.rs:166:76
894    |
895166 | pub unsafe extern "C" fn cro_tx_add_viewkey_raw(tx_ptr: CroTxPtr, viewkey: [u8; 33]) -> CroResult {
896    |                                                                            ^^^^^^^^ not FFI-safe
897    |
898    = help: consider passing a pointer to the array
899    = note: passing raw arrays by value is not FFI-safe
900
901error: `extern` fn uses type `[u8; 32]`, which is not FFI-safe
902   --> cro-clib/src/transaction_build.rs:289:11
903    |
904289 |     addr: [u8; 32],
905    |           ^^^^^^^^ not FFI-safe
906    |
907    = help: consider passing a pointer to the array
908    = note: passing raw arrays by value is not FFI-safe
909
910error: aborting due to 4 previous errors
```

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: fix ffi issue and change progress_callback for example c-code, also fix clippy issue

### CODE REVIEW

**Comment by leejw51crypto** [comment]
working on example compiling issue, will be submitted as another issue

**Comment by leejw51crypto** [comment]
i'll fix it

File: cro-clib/src/jsonrpc.rs [hunk 1]
```diff
@@ -69,7 +69,7 @@ pub unsafe extern "C" fn cro_jsonrpc_call(
     request: *const c_char,
     buf: *mut c_char,
     buf_size: usize,
-    progress_callback: Option<ProgressCallback>,
+    progress_callback: ProgressCallback,
```
Comment (yihuang) [inline cro-clib/src/jsonrpc.rs:72]: The `Option` is to handle no callback scenario.

Comment (leejw51crypto) [reply cro-clib/src/jsonrpc.rs:72]: i see, but Option<..> cannot be used in c-language.(gcc error)
it will be done by giving NULL as argument
i'll add code for that condition

Comment (leejw51crypto) [reply cro-clib/src/jsonrpc.rs]: exported callback function type, example can use it to give function pointer correctly.

Comment (leejw51crypto) [reply cro-clib/src/jsonrpc.rs]: typedef int32_t (*ProgressCallback)(uint64_t, uint64_t, uint64_t, const void*);
typedef ProgressCallback Option_ProgressCallback;

**Comment by leejw51crypto** [comment]
i'll fix clippy issue

**Comment by leejw51crypto** [comment]
i'm inspecting drone issue now

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
@leejw51crypto the drone failure may be due to #1804

**Comment by leejw51crypto** [comment]
ok
