### PR TITLE
Problem (Fix #1676): mock keypackages failing unit tests

### LINKED ISSUE #1676: Problem: mock keypackages failing unit tests
e.g. https://travis-ci.org/github/crypto-com/chain/jobs/691786944#L1177
```
test wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address ... FAILED
1178test wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address ... FAILED
1179test wallet::syncer::tests::check_wallet_syncer_app_hash_on_multiple_tx ... ignored
1180test wallet::syncer::tests::check_wallet_syncer ... FAILED
1181test wallet::syncer_logic::tests::check_syncer_logic_basic ... ok
1182test wallet::syncer_logic::tests::check_syncer_logic_tx_flow ... ok
1183
1184failures:
1185
1186---- service::sync_state_service::tests::check_sync_state_serialization stdout ----
1187thread 'service::sync_state_service::tests::check_sync_state_serialization' panicked at 'distribution validation error: KeyPackageVerifyError(CertificateVerifyError(OldAttestationReport))', test-common/src/block_generator.rs:284:29
1188stack backtrace:
1189   0: backtrace::backtrace::libunwind::trace
1190             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1191   1: backtrace::backtrace::trace_unsynchronized
1192             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
1193   2: std::sys_common::backtrace::_print_fmt
1194             at src/libstd/sys_common/backtrace.rs:78
1195   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1196             at src/libstd/sys_common/backtrace.rs:59
1197   4: core::fmt::write
1198             at src/libcore/fmt/mod.rs:1076
1199   5: std::io::Write::write_fmt
1200             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/io/mod.rs:1537
1201   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1202             at src/libstd/io/impls.rs:176
1203   7: std::sys_common::backtrace::_print
1204             at src/libstd/sys_common/backtrace.rs:62
1205   8: std::sys_common::backtrace::print
1206             at src/libstd/sys_common/backtrace.rs:49
1207   9: std::panicking::default_hook::{{closure}}
1208             at src/libstd/panicking.rs:198
1209  10: std::panicking::default_hook
1210             at src/libstd/panicking.rs:215
1211  11: std::panicking::rust_panic_with_hook
1212             at src/libstd/panicking.rs:486
1213  12: rust_begin_unwind
1214             at src/libstd/panicking.rs:388
1215  13: core::panicking::panic_fmt
1216             at src/libcore/panicking.rs:101
1217  14: core::option::expect_none_failed
1218             at src/libcore/option.rs:1272
1219  15: core::result::Result<T,E>::expect
1220             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/result.rs:963
1221  16: test_common::block_generator::TestnetSpec::gen_genesis
1222             at test-common/src/block_generator.rs:284
1223  17: test_common::block_generator::BlockGenerator::new
1224             at test-common/src/block_generator.rs:392
1225  18: test_common::block_generator::BlockGenerator::one_node
1226             at test-common/src/block_generator.rs:406
1227  19: client_core::service::sync_state_service::tests::check_sync_state_serialization
1228             at client-core/src/service/sync_state_service.rs:167
1229  20: client_core::service::sync_state_service::tests::check_sync_state_serialization::{{closure}}
1230             at client-core/src/service/sync_state_service.rs:166
1231  21: core::ops::function::FnOnce::call_once
1232             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/ops/function.rs:232
1233  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1234             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/liballoc/boxed.rs:1057
1235  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
1236             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:318
1237  24: std::panicking::try::do_call
1238             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:297
1239  25: std::panicking::try
1240             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:274
1241  26: std::panic::catch_unwind
1242             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:394
1243  27: test::run_test_in_process
1244             at src/libtest/lib.rs:541
1245  28: test::run_test::run_test_inner::{{closure}}
1246             at src/libtest/lib.rs:450
1247note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
1248
1249---- wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address stdout ----
1250thread 'wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address' panicked at 'distribution validation error: KeyPackageVerifyError(CertificateVerifyError(OldAttestationReport))', test-common/src/block_generator.rs:284:29
1251stack backtrace:
1252   0: backtrace::backtrace::libunwind::trace
1253             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1254   1: backtrace::backtrace::trace_unsynchronized
1255             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
1256   2: std::sys_common::backtrace::_print_fmt
1257             at src/libstd/sys_common/backtrace.rs:78
1258   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1259             at src/libstd/sys_common/backtrace.rs:59
1260   4: core::fmt::write
1261             at src/libcore/fmt/mod.rs:1076
1262   5: std::io::Write::write_fmt
1263             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/io/mod.rs:1537
1264   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1265             at src/libstd/io/impls.rs:176
1266   7: std::sys_common::backtrace::_print
1267             at src/libstd/sys_common/backtrace.rs:62
1268   8: std::sys_common::backtrace::print
1269             at src/libstd/sys_common/backtrace.rs:49
1270   9: std::panicking::default_hook::{{closure}}
1271             at src/libstd/panicking.rs:198
1272  10: std::panicking::default_hook
1273             at src/libstd/panicking.rs:215
1274  11: std::panicking::rust_panic_with_hook
1275             at src/libstd/panicking.rs:486
1276  12: rust_begin_unwind
1277             at src/libstd/panicking.rs:388
1278  13: core::panicking::panic_fmt
1279             at src/libcore/panicking.rs:101
1280  14: core::option::expect_none_failed
1281             at src/libcore/option.rs:1272
1282  15: core::result::Result<T,E>::expect
1283             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/result.rs:963
1284  16: test_common::block_generator::TestnetSpec::gen_genesis
1285             at test-common/src/block_generator.rs:284
1286  17: test_common::block_generator::BlockGenerator::new
1287             at test-common/src/block_generator.rs:392
1288  18: test_common::block_generator::BlockGenerator::one_node
1289             at test-common/src/block_generator.rs:406
1290  19: client_core::wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address
1291             at client-core/src/wallet/syncer.rs:916
1292  20: client_core::wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address::{{closure}}
1293             at client-core/src/wallet/syncer.rs:905
1294  21: core::ops::function::FnOnce::call_once
1295             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/ops/function.rs:232
1296  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1297             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/liballoc/boxed.rs:1057
1298  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
1299             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:318
1300  24: std::panicking::try::do_call
1301             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:297
1302  25: std::panicking::try
1303             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:274
1304  26: std::panic::catch_unwind
1305             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:394
1306  27: test::run_test_in_process
1307             at src/libtest/lib.rs:541
1308  28: test::run_test::run_test_inner::{{closure}}
1309             at src/libtest/lib.rs:450
1310note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
1311
1312---- wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address stdout ----
1313thread 'wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address' panicked at 'distribution validation error: KeyPackageVerifyError(CertificateVerifyError(OldAttestationReport))', test-common/src/block_generator.rs:284:29
1314stack backtrace:
1315   0: backtrace::backtrace::libunwind::trace
1316             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1317   1: backtrace::backtrace::trace_unsynchronized
1318             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
1319   2: std::sys_common::backtrace::_print_fmt
1320             at src/libstd/sys_common/backtrace.rs:78
1321   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1322             at src/libstd/sys_common/backtrace.rs:59
1323   4: core::fmt::write
1324             at src/libcore/fmt/mod.rs:1076
1325   5: std::io::Write::write_fmt
1326             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/io/mod.rs:1537
1327   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1328             at src/libstd/io/impls.rs:176
1329   7: std::sys_common::backtrace::_print
1330             at src/libstd/sys_common/backtrace.rs:62
1331   8: std::sys_common::backtrace::print
1332             at src/libstd/sys_common/backtrace.rs:49
1333   9: std::panicking::default_hook::{{closure}}
1334             at src/libstd/panicking.rs:198
1335  10: std::panicking::default_hook
1336             at src/libstd/panicking.rs:215
1337  11: std::panicking::rust_panic_with_hook
1338             at src/libstd/panicking.rs:486
1339  12: rust_begin_unwind
1340             at src/libstd/panicking.rs:388
1341  13: core::panicking::panic_fmt
1342             at src/libcore/panicking.rs:101
1343  14: core::option::expect_none_failed
1344             at src/libcore/option.rs:1272
1345  15: core::result::Result<T,E>::expect
1346             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/result.rs:963
1347  16: test_common::block_generator::TestnetSpec::gen_genesis
1348             at test-common/src/block_generator.rs:284
1349  17: test_common::block_generator::BlockGenerator::new
1350             at test-common/src/block_generator.rs:392
1351  18: test_common::block_generator::BlockGenerator::one_node
1352             at test-common/src/block_generator.rs:406
1353  19: client_core::wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address
1354             at client-core/src/wallet/syncer.rs:973
1355  20: client_core::wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address::{{closure}}
1356             at client-core/src/wallet/syncer.rs:962
1357  21: core::ops::function::FnOnce::call_once
1358             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/ops/function.rs:232
1359  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1360             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/liballoc/boxed.rs:1057
1361  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
1362             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:318
1363  24: std::panicking::try::do_call
1364             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:297
1365  25: std::panicking::try
1366             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:274
1367  26: std::panic::catch_unwind
1368             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:394
1369  27: test::run_test_in_process
1370             at src/libtest/lib.rs:541
1371  28: test::run_test::run_test_inner::{{closure}}
1372             at src/libtest/lib.rs:450
1373note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
1374
1375---- wallet::syncer::tests::check_wallet_syncer stdout ----
1376thread 'wallet::syncer::tests::check_wallet_syncer' panicked at 'distribution validation error: KeyPackageVerifyError(CertificateVerifyError(OldAttestationReport))', test-common/src/block_generator.rs:284:29
1377stack backtrace:
1378   0: backtrace::backtrace::libunwind::trace
1379             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1380   1: backtrace::backtrace::trace_unsynchronized
1381             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
1382   2: std::sys_common::backtrace::_print_fmt
1383             at src/libstd/sys_common/backtrace.rs:78
1384   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1385             at src/libstd/sys_common/backtrace.rs:59
1386   4: core::fmt::write
1387             at src/libcore/fmt/mod.rs:1076
1388   5: std::io::Write::write_fmt
1389             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/io/mod.rs:1537
1390   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1391             at src/libstd/io/impls.rs:176
1392   7: std::sys_common::backtrace::_print
1393             at src/libstd/sys_common/backtrace.rs:62
1394   8: std::sys_common::backtrace::print
1395             at src/libstd/sys_common/backtrace.rs:49
1396   9: std::panicking::default_hook::{{closure}}
1397             at src/libstd/panicking.rs:198
1398  10: std::panicking::default_hook
1399             at src/libstd/panicking.rs:215
1400  11: std::panicking::rust_panic_with_hook
1401             at src/libstd/panicking.rs:486
1402  12: rust_begin_unwind
1403             at src/libstd/panicking.rs:388
1404  13: core::panicking::panic_fmt
1405             at src/libcore/panicking.rs:101
1406  14: core::option::expect_none_failed
1407             at src/libcore/option.rs:1272
1408  15: core::result::Result<T,E>::expect
1409             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/result.rs:963
1410  16: test_common::block_generator::TestnetSpec::gen_genesis
1411             at test-common/src/block_generator.rs:284
1412  17: test_common::block_generator::BlockGenerator::new
1413             at test-common/src/block_generator.rs:392
1414  18: test_common::block_generator::BlockGenerator::one_node
1415             at test-common/src/block_generator.rs:406
1416  19: client_core::wallet::syncer::tests::check_wallet_syncer_impl
1417             at client-core/src/wallet/syncer.rs:732
1418  20: client_core::wallet::syncer::tests::check_wallet_syncer
1419             at client-core/src/wallet/syncer.rs:764
1420  21: client_core::wallet::syncer::tests::check_wallet_syncer::{{closure}}
1421             at client-core/src/wallet/syncer.rs:763
1422  22: core::ops::function::FnOnce::call_once
1423             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libcore/ops/function.rs:232
1424  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1425             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/liballoc/boxed.rs:1057
1426  24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
1427             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:318
1428  25: std::panicking::try::do_call
1429             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:297
1430  26: std::panicking::try
1431             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panicking.rs:274
1432  27: std::panic::catch_unwind
1433             at /rustc/5239f5c57bb6eb9e894081727f5aba0a67e89763/src/libstd/panic.rs:394
1434  28: test::run_test_in_process
1435             at src/libtest/lib.rs:541
1436  29: test::run_test::run_test_inner::{{closure}}
1437             at src/libtest/lib.rs:450
1438note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
1439
1440
1441failures:
1442    service::sync_state_service::tests::check_sync_state_serialization
1443    wallet::syncer::tests::check_handle_recover_addresses_for_transaction_not_owned_address
1444    wallet::syncer::tests::check_handle_recover_addresses_for_transaction_owned_address
1445    wallet::syncer::tests::check_wallet_syncer
1446
1447
```

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Fix reference time in block generator

### CODE REVIEW

File: chain-abci/src/staking/tx.rs [hunk 1]
```diff
@@ -35,14 +35,19 @@ impl StakingTable {
...
-        let keypackage = KeyPackage::read_bytes(&tx.node_meta.confidential_init.keypackage)
-            .ok_or(NodeJoinError::KeyPackageDecodeError)?;
-        let info = keypackage
-            .verify(&ENCLAVE_CERT_VERIFIER, block_time)
-            .map_err(NodeJoinError::KeyPackageVerifyError)?;
-        let new_isv_svn = if info.quote.report_body.isv_svn > recent_isv_svn {
-            warn!("more recent version of enclave");
-            info.quote.report_body.isv_svn
+        // FIXME
+        let new_isv_svn = if &tx.node_meta.confidential_init.keypackage != b"FIXME NODE JOIN" {
```
Comment (tomtau) [inline chain-abci/src/staking/tx.rs:39]: I'm not sure whether this can be "fixed" for the unit tests, as they may be executing on non-sgx where one can't obtain a keypackage with valid attestation payload... instead of hardcoding this on the common path, perhaps this could be put in/offloaded to the enclave bridge?
In the real environment, it'll run the full verification; in the mock, it'll skip it or run some reduced version?

File: client-rpc/src/rpc/staking_rpc.rs [hunk 2]
```diff
@@ -463,6 +462,8 @@ fn get_node_metadata(validator_name: &str, validator_pubkey: &str) -> Result<Cou
         security_contact: None,
         consensus_pubkey: TendermintValidatorPubKey::Ed25519(pubkey_bytes),
         // FIXME real keypackage
-        confidential_init: mock_confidential_init(),
+        confidential_init: ConfidentialInit {
```
Comment (tomtau) [inline client-rpc/src/rpc/staking_rpc.rs:465]: this is needed for the integration tests?

Comment (yihuang) [reply client-rpc/src/rpc/staking_rpc.rs:465]: yes, because the reference time in integration test can't be controlled, so it'll need real keypackage or other mock solutions.

File: chain-abci/src/staking/tx.rs (hunk 1 above)
Comment (yihuang) [reply chain-abci/src/staking/tx.rs:39]: Currently, the unit test can provide pre-created keypackages, with adjusted reference time(genesis/block time), it runs ok.
But for integration tests, the reference time can't adjusted easily(generated by tendermint process), so it'll be either real one or other mock solution.
The `b"FIXME NODE JOIN"` is only here for integration tests temporarily.

**Comment by yihuang** [comment]
fixed clippy warnings.

**Comment by tomtau** [comment]
bors retry
