### PR TITLE
Problem(fix #914) Unable to restore wallet with the same mnemonic words

### LINKED ISSUE #914: Problem: Unable to restore wallet with the same seed (or mnemonic words) as existing wallet.
Steps to reproduce:
```
$ chainrpc.py wallet restore "pony thank pluck sweet bless tuna couple eight stove fluid essay debate cinnamon elite only" --name Default
$ chainrpc.py wallet restore "pony thank pluck sweet bless tuna couple eight stove fluid essay debate cinnamon elite only" --name test
Traceback (most recent call last):
    ...
jsonrpcclient.exceptions.ReceivedErrorResponseError: Decryption error: Incorrect enckey: Unable to unlock stored values
```

The reason is different wallets have different encryption keys now, so it can't load the key pair created by the other wallet.

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution:
* store the (wallet_name, wallet's private_key) in `KeySerivce`
* move the (public_key, private_key) pair (used for transfer add and staking address) in `Wallet`
* extend the `root_hash` with the `wallet_name` as  storage_key to store the `multi_sig_address`
* add unit test

### CODE REVIEW

File: client-core/src/service/key_service.rs [hunk 1]
```diff
@@ -21,32 +21,32 @@ where
         KeyService { storage }
     }
 
-    /// Adds a new public-private keypair to storage
-    pub fn add_keypair(
+    /// Adds a new wallet_name-private keypair to storage
```
Comment (yihuang) [inline client-core/src/service/key_service.rs]: I think it needs to store multiple key pairs for one wallet.

File: client-core/src/service/key_service.rs [hunk 2]
```diff
@@ -21,32 +21,32 @@ where
...
+    pub fn add_wallet_private_key(
```
Comment (leejw51crypto) [inline client-core/src/service/key_service.rs]: some explanation?
what's this privatekey?

File: client-core/src/service/key_service.rs [hunk 3]
```diff
@@ -21,32 +21,32 @@ where
...
+                wallet_name.as_bytes(),
                 private_key.serialize(),
                 enckey,
             )
             .map(|_| ())
     }
 
-    /// Retrieves private key corresponding to given public key
-    pub fn private_key(
+    /// Retrieves private key corresponding to given wallet name
```
Comment (leejw51crypto) [inline client-core/src/service/key_service.rs]: one wallet, one privatekey,
1:1 right?

File: client-core/src/service/key_service.rs [hunk 4]
```diff
@@ -21,32 +21,32 @@ where
...
+        wallet_name: &str,
         private_key: &PrivateKey,
-        public_key: &PublicKey,
         enckey: &SecKey,
     ) -> Result<()> {
         self.storage
             .set_secure(
                 KEYSPACE,
-                public_key.serialize(),
+                wallet_name.as_bytes(),
```
Comment (leejw51crypto) [inline client-core/src/service/key_service.rs]: why public-key is not necessary?

File: client-core/src/service/key_service.rs [hunk 5]
```diff
@@ -21,32 +21,32 @@ where
...
             .map(|_| ())
     }
 
-    /// Retrieves private key corresponding to given public key
-    pub fn private_key(
+    /// Retrieves private key corresponding to given wallet name
+    pub fn wallet_private_key(
         &self,
-        public_key: &PublicKey,
+        wallet_name: &str,
```
Comment (leejw51crypto) [inline client-core/src/service/key_service.rs]: also publickey

Comment (leejw51crypto) [reply client-core/src/service/key_service.rs]: consider wallet_name + public_key

File: client-core/src/service/key_service.rs (hunk 2 above)
Comment (linfeng-crypto) [reply client-core/src/service/key_service.rs]: the private key is the one when a wallet created and the view key comes from this private key

File: client-core/src/service/key_service.rs (hunk 4 above)
Comment (linfeng-crypto) [reply client-core/src/service/key_service.rs]: because the public-key is the view key, already stored in `Wallet`

File: client-core/src/service/key_service.rs (hunk 3 above)
Comment (linfeng-crypto) [reply client-core/src/service/key_service.rs]: yes, the private key is the one when the wallet create, so there is only one private key.

File: client-core/src/service/key_service.rs (hunk 1 above)
Comment (linfeng-crypto) [reply client-core/src/service/key_service.rs]: mulitiple key pairs (for transfer addresses and staking address ) are stored in Wallet.

File: client-core/src/service/key_service.rs (hunk 2 above)
Comment (leejw51crypto) [reply client-core/src/service/key_service.rs]: if it's just one wallet, set_wallet_viewkey_private?

**Comment by linfeng-crypto** [comment]
> from a quick look, it seems all right.
> since this will make it incompatible with old client data, could you add an entry to breaking changes (of unreleased 0.4.0) in CHANGELOG.md ?

Ok

File: client-core/src/service/key_service.rs (hunk 1 above)
Comment (yihuang) [reply client-core/src/service/key_service.rs]: So I think `KeyService` can be removed now since key pairs are in `Wallet`?

Comment (linfeng-crypto) [reply client-core/src/service/key_service.rs]: but the private key is not stored in Wallet, how do you think we move all the associated items (like key pairs, private key, multisign_address) into the `Wallet`, because all the `items`  can be accessed with `enckey`(+ wallet_name) just like `Wallet`, we currently stored them in different place, if we want to get them, we first get the `Wallet`, then use the key in the wallet to get the value, it's not convenient.
