### PR TITLE
Problem (Fix #1703): incorrect tree hashing in mls modules

### LINKED ISSUE #1703: Problem: incorrect tree hashing in mls modules
1. some of the tree math methods are to be fixed in the spec: https://github.com/mlswg/mls-protocol/pull/327/files#diff-a87cc9081154f564150420544170f1c9L2898

2. currently, the code operates on plain usize, but it's potentially error-prone, as there are two kinds of indices (node position vs leaf position) -- similarly to the reference implementation: https://github.com/cisco/go-mls/blob/master/tree-math.go#L28 it'll be good to have opaque types (`LeafSize` and `NodeSize` as with Rust naming conventions?) to distinguish between these two

3. tree implementation misses some parts, the existing code may be wrong (e.g. due to 2) -- passing node index instead of leaf index and vice versa) and integrity checking isn'd done in the welcome message processing:
> For each non-empty parent node, verify that exactly one of the node's children are non-empty and have the hash of this node set as their parent_hash value (if the child is another parent) or has a parent_hash extension in the KeyPackage containing the same value (if the child is a leaf).
>
>For each non-empty leaf node, verify the signature on the KeyPackage.

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Implement ratchet tree evolution
- Populate DirectPath for init_commit
- support apply the path secrets when apply commit message

### CODE REVIEW

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 1]
```diff
@@ -77,12 +78,7 @@ impl Codec for ApplicationContext {
 }
 
 /// Additional methods for Kdf
-pub trait HkdfExt<D>
-where
-    D: Input + BlockInput + FixedOutput + Reset + Default + Clone,
-    D::BlockSize: ArrayLength<u8>,
-    D::OutputSize: ArrayLength<u8>,
-{
+pub trait HkdfExt {
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:81]: some comment about HkdftExt , can be replaced with fullword ?

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 2]
```diff
@@ -296,15 +292,88 @@ impl CipherSuite {
...
+    ) -> Result<Vec<u8>, InvalidLength> {
+        match self {
+            CipherSuite::MLS10_128_DHKEMP256_AES128GCM_SHA256_P256 => Hkdf::<Sha256>::new(
+                None, secret,
+            )
+            .expand_label(group_context_hash, label, context, length),
+        }
+    }
+
+    pub fn secret_size(self) -> u16 {
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:324]: key_pair secret?

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 3]
```diff
@@ -153,13 +149,13 @@ where
 }
 
 impl CipherSuite {
-    pub fn aead_key_len(&self) -> usize {
+    pub fn aead_key_len(self) -> usize {
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:152]: comment of aead

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 4]
```diff
@@ -296,15 +292,88 @@ impl CipherSuite {
...
+        }
+    }
+
+    pub fn secret_size(self) -> u16 {
+        match self {
+            CipherSuite::MLS10_128_DHKEMP256_AES128GCM_SHA256_P256 => 32,
+        }
+    }
+
+    pub fn derive_private_key(
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:330]: from Ciphersuites def?

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 5]
```diff
@@ -278,7 +274,7 @@ impl CipherSuite {
 
     /// TODO: use generic array?
     pub fn encrypt_group_info(
-        &self,
+        self,
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:277]: just &[u8] is fastest, not necessary to use generic array

File: chain-tx-enclave-next/mls/src/ciphersuite.rs [hunk 6]
```diff
@@ -296,15 +292,88 @@ impl CipherSuite {
     }
 
     /// TODO: use generic array?
-    pub fn hash(&self, data: &[u8]) -> Vec<u8> {
+    pub fn hash(self, data: &[u8]) -> Vec<u8> {
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/ciphersuite.rs:295]: this is fine, not necessary to use generic array

File: chain-tx-enclave-next/mls/src/group.rs [hunk 7]
```diff
@@ -174,19 +175,38 @@ impl GroupAux {
...
+        let (path_nodes, parent_hash, commit_secret) =
+            updated_tree.encap(&updated_group_context.get_encoding(), leaf_secret);
+
+        // update keypackage's parent_hash extension
+        self.owned_kp
+            .keypackage
+            .payload
+            .put_extension(&ext::ParentHashExt(parent_hash));
+        self.owned_kp.update_signature();
+        updated_tree.set_my_package(self.owned_kp.keypackage.clone());
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/group.rs:196]: > The generator of the Commit starts by using the HPKE secret key "leaf_hpke_secret" associated with the new leaf KeyPackage (see {{key-packages}}) to compute "path_secret[0]"

File: chain-tx-enclave-next/mls/src/key.rs [hunk 8]
```diff
@@ -100,6 +104,14 @@ impl HPKEPrivateKey {
     pub fn kex_secret(&self) -> &<hpke::kex::DhP256 as hpke::KeyExchange>::PrivateKey {
         &self.0
     }
+
+    pub fn unmarshal(secret: &[u8]) -> Result<Self, HpkeError> {
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/key.rs:108]: consider `decode` for unmarshal, because we're using `encode`, `decode` terms

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 4 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:330]: probably fixme or change to use https://github.com/cfrg/draft-irtf-cfrg-hpke/blob/master/draft-irtf-cfrg-hpke.md#derivekeypair-derive-key-pair

File: chain-tx-enclave-next/mls/src/keypackage.rs [hunk 9]
```diff
@@ -81,6 +81,19 @@ impl KeyPackagePayload {
         ))
     }
 
+    /// insert or update extension
+    pub fn put_extension<T: MLSExtension>(&mut self, ext: &T) {
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/keypackage.rs:85]: pub fn put_extension(&mut self, ext: &MLSExtension) { 
is simpler

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 10]
```diff
@@ -350,7 +390,148 @@ impl Tree {
...
+            my_pos: LeafSize(0),
         })
     }
+
+    /// spec: draft-ietf-mls-protocol.md#ratchet-tree-evolution
+    ///
+    /// update path secrets
+    ///
+    /// returns: direct path nodes, parent_hash, root_secret
+    pub fn encap(
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/tree.rs:402]: full word for `encap`

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 11]
```diff
@@ -350,7 +390,148 @@ impl Tree {
...
+    match node {
+        Node::Leaf(kp) => cs.hash(
+            &LeafNodeHashInput {
+                node_index: index.0 as u32,
+                key_package: kp.clone(),
+            }
+            .get_encoding(),
+        ),
+        Node::Parent(pn) => {
+            let left_index = index.left().unwrap();
```
Comment (leejw51crypto) [inline chain-tx-enclave-next/mls/src/tree.rs:492]: expect()?

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 4 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:330]: the problem here is that not all secrets from that "key pair expand label" may be valid, so the unmarshal may panic

File: chain-tx-enclave-next/mls/src/key.rs [hunk 12]
```diff
@@ -88,6 +91,7 @@ impl Codec for HPKEPublicKey {
 
 /// p-256 private key
 /// used for obtaining the initial sealed secrets (HPKE)
+#[derive(Clone)]
 pub struct HPKEPrivateKey(<hpke::kex::DhP256 as hpke::KeyExchange>::PrivateKey);
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/key.rs:95]: is this needed to be clone?

File: chain-tx-enclave-next/mls/src/group.rs (hunk 7 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/group.rs:196]: init key is to be updated -- https://github.com/cisco/go-mls/blob/master/state.go#L370 ?

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 13]
```diff
@@ -350,7 +390,148 @@ impl Tree {
...
+
+    /// spec: draft-ietf-mls-protocol.md#ratchet-tree-evolution
+    ///
+    /// update path secrets
+    ///
+    /// returns: direct path nodes, parent_hash, root_secret
+    pub fn encap(
+        &mut self,
+        ctx: &[u8],
+        leaf_secret: Vec<u8>,
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/tree.rs:405]: SecretVec?

File: chain-tx-enclave-next/mls/Cargo.toml [hunk 14]
```diff
@@ -19,6 +19,7 @@ aead = "0.2.0"
 rand = "0.7"
 ra-client = { path = "../enclave-ra/ra-client" }
 subtle = "2.2.3"
+rand_core = "0.5"
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/Cargo.toml:22]: why rand_core? isn't that exposed from rand?

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 10 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/tree.rs:402]: or something different -- `Encap` has already a defined meaning in HPKE, but here it's something else

File: chain-tx-enclave-next/mls/src/key.rs (hunk 8 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/key.rs:108]: these are keywords used in the spec

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 6 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:295]: generic array would prevent some problems at compile-time, because there are various `Vec<u8>` (hashes, secrets, nonces, pubkeys...) which can be quite error-prone

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 5 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:277]: generic array is meant rather for welcome_key, welcome_nonce ... not the (variable-length) plaintext input

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 1 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:81]: it has a comment "Additional methods for Kdf".
It expands the "Hkdf" trait with extra methods defined in: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#key-schedule

Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:81]: maybe it can reference it?

File: chain-tx-enclave-next/mls/src/group.rs (hunk 7 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/group.rs:196]: > When used as InitKeys, KeyPackages are intended to be used only once and SHOULD NOT be reused except in case of last resort.

File: chain-tx-enclave-next/mls/src/keypackage.rs (hunk 9 above)
Comment (devashishdxt) [reply chain-tx-enclave-next/mls/src/keypackage.rs:85]: Maybe use `pub fn put_extension(&mut self: ext: &impl MLSExtension)`?

Comment (yihuang) [reply chain-tx-enclave-next/mls/src/keypackage.rs:85]: done

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 10 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs:402]: maybe "evolve"

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 11 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs:492]: done

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 2 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:324]: The [go-mls](https://github.com/cisco/go-mls/blob/master/crypto.go#L69) used the name `SecretSize`, so

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 4 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:330]: added a FIXME for now, the go version seems don't handle this currently.

File: chain-tx-enclave-next/mls/src/group.rs (hunk 7 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/group.rs:196]: done

File: chain-tx-enclave-next/mls/src/key.rs (hunk 12 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/key.rs:95]: removed

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 13 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs:405]: done

File: chain-tx-enclave-next/mls/Cargo.toml (hunk 14 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/Cargo.toml:22]: removed

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 2 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:325]: so what's this `secret_size` if not key pair secret size? the output hash length?

Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:325]: It’s used by expand label “path”, when generating path secrets.

**Comment by yihuang** [comment]
support apply path secrets when apply commit message now, existing unit tests passed.

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 1 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:83]: done

File: chain-tx-enclave-next/mls/src/key.rs (hunk 12 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/key.rs:96]: The `Clone` is added back, because we need to store private keys inside tree, and tree need to be able to be cloned.

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 2 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#ratchet-tree-evolution

`KEM.Nsk` -- Nsk is the length of the secret key, so should be the same `keypair_secret_size`?

Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: some of this changed, it may be good to put Git commit sha of spec this refers to

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 4 above)
Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:339]: that definitions isn't longer in the spec?

Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:339]: that expand_label with "key pair"?

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 2 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: "Each ciphersuite has a `Derive-Key-Pair` function that maps octet strings of
length `Nsk` (a KEM-specific constant defined by HPKE) to HPKE key pairs", it seems they are still different?
And in go-mls, the [P521_AES256GCM_SHA512_P521](https://github.com/cisco/go-mls/blob/master/crypto.go#L108) has SecretSize 64, but the [DHKEM_P256](https://github.com/cisco/go-mls/blob/master/crypto.go#L292) has keyPairSecretSize 32.

Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: > some of this changed, it may be good to put Git commit sha of spec this refers to

update the sha in lib.rs to refer to current master?

Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: > "Each ciphersuite has a `Derive-Key-Pair` function that maps octet strings of
> length `Nsk` (a KEM-specific constant defined by HPKE) to HPKE key pairs", it seems they are still different?
> And in go-mls, the [P521_AES256GCM_SHA512_P521](https://github.com/cisco/go-mls/blob/master/crypto.go#L108) has SecretSize 64, but the [HPKEKEM](https://github.com/cisco/go-mls/blob/master/crypto.go#L292) has keyPairSecretSize 32.

66, not 32: https://github.com/cfrg/draft-irtf-cfrg-hpke/blob/master/draft-irtf-cfrg-hpke.md#key-encapsulation-mechanisms-kems-kem-ids

`shared_secret_size`? I'd need to read through more in detail whether that context is correct

Comment (tomtau) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: as HPKE library doesn't implement P-521 or X448 yet, I'm not sure if it even distinguishes these sizes :) but still good to keep it consistent and distinguish them if that's in the spec

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 4 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:339]: "This function is defined to be HPKE's `DeriveKeyPair` function.", I think it refers to the [hpke spec](https://github.com/cfrg/draft-irtf-cfrg-hpke/blob/master/draft-irtf-cfrg-hpke.md#derivekeypair-derive-key-pair) now.

Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:339]: The DeriveKeyPair function should ideally implemented in hpke library?

Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs]: the hpke library just implemented derive_keypair, we changed to use that now.

File: chain-tx-enclave-next/mls/src/ciphersuite.rs (hunk 2 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/ciphersuite.rs:327]: oh, I guess they have a bug here to [use DHKEM_P256 in ciphersuite P521_AES256GCM_SHA512_P521](https://github.com/cisco/go-mls/blob/master/crypto.go#L109)

**Comment by yihuang** [comment]
> maybe splitting the tree into private and public portions similarly to https://github.com/cisco/go-mls/pull/71/files#diff-53faa623cefecaf31c5a72febc6526c9R363 ?
> need to yet read through the code in more detail, as some spec parts changed a bit

how about do this in another pr, I think we need better code change to make the tree implementation more robust [sketched here](https://gist.github.com/yihuang/3155363033f6b7c4c17f4b9d42894df2)

**Comment by tomtau** [comment]
> > maybe splitting the tree into private and public portions similarly to https://github.com/cisco/go-mls/pull/71/files#diff-53faa623cefecaf31c5a72febc6526c9R363 ?
> > need to yet read through the code in more detail, as some spec parts changed a bit
> 
> how about do this in another pr, I think we need more code changes to make the tree implementation more robust [sketched here](https://gist.github.com/yihuang/3155363033f6b7c4c17f4b9d42894df2)

should be ok, I'll try to do a final read of this PR later today -- these other code improvements can be in a different PR

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 15]
```diff
@@ -335,34 +441,264 @@ impl Tree {
...
+                right_hash,
+            }
+            .get_encoding()
         }
+    };
+    cs.hash(&payload)
+}
+
+/// no blank nodes return
+fn resolve(nodes: &[Node], index: NodeSize) -> Vec<NodeSize> {
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/tree.rs:677]: could be good to link "Ratchet Tree Nodes" section -- I was trying to search "resolve" where it is defined

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 16]
```diff
@@ -335,34 +441,264 @@ impl Tree {
...
+                        .expect("decrypt failed");
+                    return (ancestor, SecretVec::new(secret));
+                }
+            }
+            panic!("don't find private key to decrypt secret");
+        }
+    }
+
+    /// returns (leaf_parent_hash, commit_secret)
+    pub fn apply_path_secrets(
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/tree.rs:586]: "Synchronizing Views of the Tree"?

File: chain-tx-enclave-next/mls/src/tree.rs [hunk 17]
```diff
@@ -335,34 +441,264 @@ impl Tree {
...
+        for node_index in overlap.direct_path(leaf_len).iter() {
+            last_secret = self
+                .cs
+                .expand_label(&last_secret, vec![], "path", &[], self.cs.secret_size())
+                .expect("invalid length");
+            self.nodes[node_index.0]
+                .parent_node_mut()
+                .expect("implant invalid node")
+                .set_secret(self.cs, &last_secret);
+        }
```
Comment (tomtau) [inline chain-tx-enclave-next/mls/src/tree.rs:622]: A bit confused about this part -- my assumption is, as this is called by the recipient in processing commit in group init, that this is "Synchronizing Views of the Tree".
There's one step:
> The recipient SHOULD verify that the received public keys agree with the public keys derived from the new path_secret values.

I'm more sure whether that's done?

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 15 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs:677]: done

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 16 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs:586]: done

File: chain-tx-enclave-next/mls/src/tree.rs (hunk 17 above)
Comment (yihuang) [reply chain-tx-enclave-next/mls/src/tree.rs]: Changed the `set_secret` to `set_secret_verify_public`, the verification is done inside. the public key is updated in `merge_public_key`.

**Comment by yihuang** [comment]
> looks ok -- there may be one step missing or I missed that when reading the code -- in general, it'd be good to add pointers to spec in the more involved parts

Fixed, also changed the error types to be more specific.

**Comment by yihuang** [comment]
> one small clippy fix: https://travis-ci.org/github/crypto-com/chain/jobs/699644837#L1837

done

**Comment by tomtau** [comment]
bors retry
