### PR TITLE
Problem: (fix #1177) chain-abci doesn't work with Tendermint v0.33.*

### LINKED ISSUE #1177: Problem: chain-abci doesn't work with Tendermint v0.33.*
https://github.com/crypto-com/chain/pull/1176

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution:
* updata abci vertion to 0.7
* use the tendermint-rs verion v0.33

### CODE REVIEW

**Comment by tomtau** [comment]
bors try

File: chain-core/src/init/config.rs [hunk 1]
```diff
@@ -80,7 +80,7 @@ impl fmt::Display for DistributionError {
 
 /// Initial configuration ("app_state" in genesis.json of Tendermint config)
 /// TODO: reward/treasury config, extra validator config...
-#[derive(Debug, PartialEq, Eq, Clone)]
+#[derive(Debug, PartialEq, Eq, Default, Clone)]
```
Comment (tomtau) [inline chain-core/src/init/config.rs:83]: why are defaults added to chain-core?

File: client-common/src/tendermint/lite.rs [hunk 2]
```diff
@@ -8,7 +8,7 @@ use crate::Result as CommonResult;
 
 ///
 #[derive(Clone, Debug, Deserialize, Serialize)]
-pub struct TrustedState(pub(crate) Option<lite::TrustedState<SignedHeader, Header>>);
+pub struct TrustedState(pub Option<lite::TrustedState<SignedHeader, Header>>);
```
Comment (tomtau) [inline client-common/src/tendermint/lite.rs:11]: why not pub(crate)?

File: client-common/src/tendermint/rpc_client/async_rpc_client.rs [hunk 3]
```diff
@@ -147,7 +147,7 @@ impl AsyncRpcClient {
     /// TODO: Usage of `Vec` can be removed once we execute it in a purely async context
     pub async fn call_batch<T>(&self, batch_params: &[(&str, Vec<Value>)]) -> Result<Vec<T>>
     where
-        for<'de> T: Deserialize<'de>,
+        for<'de> T: Deserialize<'de> + std::fmt::Debug,
```
Comment (tomtau) [inline client-common/src/tendermint/rpc_client/async_rpc_client.rs:150]: is that debug needed?

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs [hunk 4]
```diff
@@ -116,7 +116,12 @@ impl SyncRpcClient {
         heights: T,
     ) -> Result<Vec<ValidatorsResponse>> {
         let params = heights
-            .map(|height| ("validators", vec![json!(height.to_string())]))
+            .map(|height| {
+                (
+                    "validators",
+                    vec![json!(height.to_string()), json!("0"), json!("100")],
```
Comment (tomtau) [inline client-common/src/tendermint/rpc_client/sync_rpc_client.rs:122]: what's that 0 and 100? paging?

File: client-common/src/tendermint/lite.rs (hunk 2 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/lite.rs:11]: Oh, that just used to get the `Option<...>` to debug, I'll rollback.

File: client-common/src/tendermint/rpc_client/async_rpc_client.rs (hunk 3 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/rpc_client/async_rpc_client.rs:150]: just for debugging, I'll remove.

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs (hunk 4 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:122]: yes, the rpc call changed, if not add 0, 100, there will be error.

**Comment by linfeng-crypto** [comment]
> integration tests fail:
> 
> ```
> ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 209	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 210	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 211	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 212	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 213	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 214	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 215	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 216	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 217	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 218	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 219	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> 220	
> ```

we need use tendermint v0.33 binary, the genesis also different with the old version.

File: chain-core/src/init/config.rs (hunk 1 above)
Comment (linfeng-crypto) [reply chain-core/src/init/config.rs:83]: there seems to be an error when deserializing something if not add Default, I remember, I'll check again.

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs (hunk 4 above)
Comment (calvinaco) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:122]: `page` and `per_page`? I think we shouldn't have an assumptions of 100 validators?

Comment (linfeng-crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:122]: https://docs.tendermint.com/master/rpc/#/Info/validators

File: client-common/src/tendermint/types/block_results.rs [hunk 5]
```diff
@@ -360,106 +273,59 @@ mod tests {
...
-                    }]),
-                    end_block: None,
-                },
-            };
-
+            let response_str = r#"{"height": "37", "txs_results": [{"code": 0, "data": null, "log": "", "info": "", "gasWanted": "0", "gasUsed": "0", "events": [{"type": "valid_txs", "attributes": [{"key": "ZmVl", "value": "MC4wMDAwMDMwNw=="}, {"key": "YWNjb3VudA==", "value": "MHgzMzUwMmVkMzlkMGM0ZTIwNDRmYjM3ZmRjZDUxNjE0OTNmNTkwMGMz"}, {"key": "dHhpZA==", "value": "ZjFmNzNkNmFjZWMyMTExOGRkMWUzNmY2ODRhYWUyMmM2Y2IxN2ZjNTFhZGEzNGEzNDIzMDlkNTMxY2I5YmU4ZA=="}]}], "codespace": ""}], "begin_block_events": null, "end_block_events": [{"type": "block_filter", "attributes": [{"key": "ZXRoYmxvb20=", "value": "AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="}]}], "validator_updates": null, "consensus_param_updates": null}"#;
+            //            let response_str = r#"
```
Comment (calvinaco) [inline client-common/src/tendermint/types/block_results.rs:277]: Is this comment still needed?

File: client-common/src/tendermint/types/block_results.rs [hunk 6]
```diff
@@ -360,106 +273,59 @@ mod tests {
...
+            let block_results: BlockResultsResponse =
+                serde_json::from_str(response_str).expect("invalid response str");
             let target_account = StakedStateAddress::from(
-                RedeemAddress::from_str("0xe4a2a719ca933d3f79a8506aa96cefde3405b0a7").unwrap(),
-            );
-            let result = block_results.contains_account(&target_account);
-            assert!(result.is_ok());
-            assert_eq!(true, result.unwrap());
-        }
-
```
Comment (calvinaco) [inline client-common/src/tendermint/types/block_results.rs:388]: Any reason to remove the following test cases?

File: client-core/src/service/sync_state_service.rs [hunk 7]
```diff
@@ -182,12 +186,11 @@ mod tests {
...
+        //        let state: SyncState = serde_json::from_str(s).unwrap();
+        let s1 = serde_json::to_string_pretty(&state).unwrap();
+        let state2: std::result::Result<SyncState, _> = serde_json::from_str(&s1);
+        let bytes = state.encode();
+        let _state1 = SyncState::decode(&mut bytes.as_slice()).unwrap();
```
Comment (calvinaco) [inline client-core/src/service/sync_state_service.rs:194]: Where is the assertion? And perhaps give some more meaningful variable names for readability.

File: client-core/src/wallet/syncer.rs [hunk 8]
```diff
@@ -327,7 +328,8 @@ impl<'a, S: SecureStorage, C: Client, D: TxDecryptor, F: FnMut(ProgressReport) -
 
             let range = chunk.collect::<Vec<u64>>();
 
-            if self.env.enable_fast_forward {
+            //if self.env.enable_fast_forward {
+            if true {
```
Comment (calvinaco) [inline client-core/src/wallet/syncer.rs:332]: Is this for debug?

File: client-rpc/src/program.rs [hunk 9]
```diff
@@ -73,7 +73,7 @@ pub struct Options {
 
 #[allow(dead_code)]
 pub fn run_cli() {
-    env_logger::init();
+    //    env_logger::init();
```
Comment (calvinaco) [inline client-rpc/src/program.rs:76]: Any reason to disable env logger?

**Comment by yihuang** [comment]
> > integration tests fail:
> > ```
> > ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 209	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 210	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 211	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 212	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 213	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 214	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 215	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 216	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 217	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 218	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 219	ERROR: Failed to create node: Error reading GenesisDoc at /drone/src/integration-tests/data/node0/tendermint/config/genesis.json: EvidenceParams.MaxAge must be greater than 0. Got 0
> > 220	
> > ```
> 
> we need to use tendermint v0.33 binary, the genesis also different with the old version.

Can you modify the tendermint version number in the `Dockerfile` in root directory, line 16 and line 44.

File: integration-tests/bot/chainbot.py [hunk 10]
```diff
@@ -348,7 +348,8 @@ async def gen_genesis(cfg):
                 "time_iota_ms": "1000"
             },
             "evidence": {
-                "max_age": "100000"
+               "max_age_num_blocks": "100000",
+               "max_age_duration": "172800000000000"
```
Comment (yihuang) [inline integration-tests/bot/chainbot.py:352]: What's the unit of `max_age_duration`, I think we have an assumption that `unbonding_period > max_age_duration`.

File: test-common/src/block_generator.rs [hunk 11]
```diff
@@ -640,19 +649,21 @@ mod tests {
...
-            &gen.validators,
-            &gen.validators,
-            lite::TrustThresholdFraction::new(1, 3).unwrap(),
-            Duration::from_secs(10000),
-            SystemTime::now(),
-        )
-        .expect("verify failed");
+        */
+
+        //FIXME: use new interface in tendermint v0.33 instead of verify_single
```
Comment (yihuang) [inline test-common/src/block_generator.rs:654]: I think the lite client API already migrated to tendermint-rs master, what's the difference in v0.33 on this?

File: client-core/src/wallet/syncer.rs (hunk 8 above)
Comment (linfeng-crypto) [reply client-core/src/wallet/syncer.rs:332]: yes, I'll remove it

File: test-common/src/block_generator.rs (hunk 11 above)
Comment (linfeng-crypto) [reply test-common/src/block_generator.rs:654]: v0.33 removed the interface and add some other similar interfaces, but the arguments are different, the logic also has some difference, I'm not clear about the logic and I think this function is very important, so  I add FIXME here, maybe we can fix it in other PR.

File: integration-tests/bot/chainbot.py (hunk 10 above)
Comment (linfeng-crypto) [reply integration-tests/bot/chainbot.py:352]: I use the default value of the new tendermint's config. we can find it in change log:
https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md

File: client-rpc/src/program.rs (hunk 9 above)
Comment (linfeng-crypto) [reply client-rpc/src/program.rs:76]: It's a mistake. I'll recover it.

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs (hunk 4 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:122]: default is 30, the max is 100, I don't know what value should be used here, I used the max value.

File: client-common/src/tendermint/types/block_results.rs (hunk 5 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/types/block_results.rs:277]: no, I'll remove it.

File: client-common/src/tendermint/types/block_results.rs (hunk 6 above)
Comment (linfeng-crypto) [reply client-common/src/tendermint/types/block_results.rs:388]: yeah, most of the test cases in this file is testing the invalid value of `Attribute` in the `BlockResults` and `BlockResults` defined in this file. 

Now, we use `BlockResultsResponse` directly which defined in `tendermint-rs`, and we query tendermint to get the `BlockResultsResponse`, I don't think tendermint will give us one which value is invalid.

File: client-core/src/service/sync_state_service.rs (hunk 7 above)
Comment (linfeng-crypto) [reply client-core/src/service/sync_state_service.rs]: added one.

**Comment by tomtau** [comment]
bors try

File: client-common/src/tendermint/types.rs [hunk 12]
```diff
@@ -24,7 +24,7 @@ pub use tendermint::{
 };
 
 /// crypto-com instantiated genesis type
-pub type Genesis = GenericGenesis<InitConfig>;
+pub type Genesis = GenericGenesis<Option<InitConfig>>;
```
Comment (yihuang) [inline client-common/src/tendermint/types.rs:27]: Is this `Option` needed?

File: client-core/src/service/sync_state_service.rs [hunk 13]
```diff
@@ -1,14 +1,14 @@
...
+use parity_scale_codec::{Decode, Encode};
+use serde::{Deserialize, Serialize};
+use tendermint::validator;
 
 /// key space of wallet sync state
 const KEYSPACE: &str = "core_wallet_sync";
 
 /// Sync state for wallet
-#[derive(Debug, Encode, Decode)]
+#[derive(Debug, Serialize, Deserialize, Encode, Decode)]
```
Comment (yihuang) [inline client-core/src/service/sync_state_service.rs:11]: Where are these two instances used?

File: test-common/src/block_generator.rs (hunk 11 above)
Comment (yihuang) [reply test-common/src/block_generator.rs:654]: > v0.33 removed the interface and add some other similar interfaces, but the arguments are different, the logic also has some difference, I'm not clear about the logic and I think this function is very important, so I add FIXME here, maybe we can fix it in other PR.

I think this API still exists with the same signature?
https://github.com/crypto-com/tendermint-rs/blob/v0.33/tendermint/src/lite/verifier.rs#L228

File: client-common/src/tendermint/types.rs (hunk 12 above)
Comment (tomtau) [reply client-common/src/tendermint/types.rs:27]: Before in tendermint-rs, it had a field `Option<AppState>` -- now the type changed to `AppState`, so it'd require Default implementation `AppState` / `InitConfig`.
I think Option may be clearer, as it'll be immediate that the app_state was missing or incorrect in json rather than some arbitrary default value?

File: Dockerfile [hunk 14]
```diff
@@ -13,7 +13,7 @@ RUN set -e; \
     apt-get install -y libzmq3-dev libssl1.1 libprotobuf10 libsgx-launch libsgx-urts libsgx-epid libsgx-quote-ex; \
     rm -rf /var/lib/apt/lists/*
 
-COPY --from=tendermint/tendermint:v0.32.9 /usr/bin/tendermint /usr/bin/tendermint
```
Comment (tomtau) [inline Dockerfile:16]: Line 44 also needs to be changed?

File: test-common/src/block_generator.rs [hunk 15]
```diff
@@ -314,15 +316,20 @@ impl TestnetSpec {
...
                 validator: consensus::params::ValidatorParams {
                     pub_key_types: vec![public_key::Algorithm::Ed25519],
                 },
             },
             validators,
-            app_hash: Some(Hash::new(hash::Algorithm::Sha256, &app_hash).unwrap()),
+            app_hash: Hash::new(hash::Algorithm::Sha256, &app_hash)
+                .unwrap()
+                .as_bytes()
+                .to_vec(),
```
Comment (yihuang) [inline test-common/src/block_generator.rs:332]:
```suggestion
            app_hash: app_hash.to_vec(),
```

File: test-common/src/block_generator.rs [hunk 16]
```diff
@@ -449,15 +458,16 @@ impl BlockGenerator {
...
             last_commit_hash: None,
             data_hash: None,
             validators_hash: self.validators.hash(),
             next_validators_hash: self.validators.hash(),
             consensus_hash,
-            app_hash: last_state.last_apphash.to_vec(),
+            app_hash: Hash::new(hash::Algorithm::Sha256, &last_state.last_apphash)
+                .unwrap()
+                .as_bytes()
+                .to_vec(),
```
Comment (yihuang) [inline test-common/src/block_generator.rs:470]:
```suggestion
            app_hash: last_state.last_apphash.to_vec(),
```

File: test-common/src/block_generator.rs (hunk 11 above)
Comment (tomtau) [reply test-common/src/block_generator.rs:654]: same here https://github.com/informalsystems/tendermint-rs/blob/tendermint/v0.33/tendermint/src/lite/verifier.rs#L228 ?

File: Dockerfile (hunk 14 above)
Comment (linfeng-crypto) [reply Dockerfile:16]: yes, I'll do that.

File: client-core/src/service/sync_state_service.rs (hunk 13 above)
Comment (linfeng-crypto) [reply client-core/src/service/sync_state_service.rs:11]: It's for debugging, I'll remove.

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
I guess the images on docker hub will need to be updated, I'll try

**Comment by tomtau** [comment]
bors retry

File: test-common/src/block_generator.rs (hunk 11 above)
Comment (linfeng-crypto) [reply test-common/src/block_generator.rs:648]: yeah, I'll check again.

Comment (linfeng-crypto) [reply test-common/src/block_generator.rs:648]: I need to fix `gen_block()` to make this test pass.

File: .drone.yml [hunk 17]
```diff
@@ -8,23 +8,23 @@ platform:
 
 steps:
 - name: build
-  image: cryptocom/chain-test:v1.1.1
+  image: cryptocom/chain-test:latest
```
Comment (yihuang) [inline .drone.yml:11]: We need to increment the version number after pushed the image.

**Comment by tomtau** [comment]
bors retry

**Comment by linfeng-crypto** [comment]
> multinode integration test fails:
> 
> ```
> Traceback (most recent call last):
> 110	  File "./multinode/join_test.py", line 45, in <module>
> 111	    wait_for_validators(rpc, 3)
> 112	  File "/drone/src/integration-tests/multinode/common.py", line 34, in wait_for_validators
> 113	    n = len(rpc.chain.validators()['validators'])
> 114	  File "/drone/src/integration-tests/bot/chainrpc.py", line 283, in validators
> 115	    return self.call_chain('validators', str(height) if height is not None else None)
> 116	  File "/drone/src/integration-tests/bot/chainrpc.py", line 62, in call_chain
> 117	    rsp = request(self.chain_rpc_url, method, *args, **kwargs)
> 118	  File "/drone/src/drone/venv/lib/python3.8/site-packages/jsonrpcclient/__init__.py", line 8, in request
> 119	    return HTTPClient(endpoint).request(*args, **kwargs)
> 120	  File "/drone/src/drone/venv/lib/python3.8/site-packages/apply_defaults/decorators.py", line 13, in wrapper
> 121	    return function(self, *args, **kwargs)
> 122	  File "/drone/src/drone/venv/lib/python3.8/site-packages/jsonrpcclient/client.py", line 229, in request
> 123	    return self.send(
> 124	  File "/drone/src/drone/venv/lib/python3.8/site-packages/apply_defaults/decorators.py", line 13, in wrapper
> 125	    return function(self, *args, **kwargs)
> 126	  File "/drone/src/drone/venv/lib/python3.8/site-packages/jsonrpcclient/client.py", line 177, in send
> 127	    raise ReceivedErrorResponseError(response.data)
> 128	jsonrpcclient.exceptions.ReceivedErrorResponseError: Invalid params
> ```

It seems that the `validators` rpc parameters is not fixed in chainrpc.py, I'll check.

File: .drone.yml (hunk 17 above)
Comment (linfeng-crypto) [reply .drone.yml:11]: It does not matter, Tomas can cover for that.

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
```

[2020-04-17T10:41:41Z ERROR client_rpc::server] Tendermint RPC error: Error while calling tendermint RPC call
--
484 | => Unable to deserialize `block_results` from JSON-RPC response for params: [String("6")]
485

```

**Comment by tomtau** [comment]
bors try
