### PR TITLE
Problem (Fix #1248): crash with withdraw transaction

### LINKED ISSUE #1248: Problem: crash with withdraw transaction
A new crash was discovered for fuzzing target abci-cycle.
Here is a snippet of the log:
```
ys-0.3.1/src/lib.rs:51:8
FUZZER:     #11 0x55f74d1e9e04 in std::panicking::rust_panic_with_hook::hfbb2ba09ce220371 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:474:16
FUZZER:     #12 0x55f74d1e991a in rust_begin_unwind /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:378:4
FUZZER:     #13 0x55f74d219c90 in core::panicking::panic_fmt::hebebbd4f16e23867 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libcore/panicking.rs:85:13
FUZZER:     #14 0x55f74d219872 in core::option::expect_failed::h57b129705028de09 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libcore/option.rs:1203:4
FUZZER:     #15 0x55f74815939b in core::option::Option$LT$T$GT$::expect::hecee96506a6e6bfe /rustc/834bc5650acf7019a53b409db68986857822812c/src/libcore/option.rs:347:20
FUZZER:     #16 0x55f748343daf in _$LT$chain_abci..enclave_bridge..mock..MockClient$u20$as$u20$chain_abci..enclave_bridge..EnclaveProxy$GT$::process_request::h8b180fc9271dd4a3 /drone/src/chain-abci/src/enclave_bridge/mock.rs:268:28
FUZZER:     #17 0x55f747c2c0e9 in chain_abci::storage::verify_enclave_tx::hbea80ef5d56f6f6b /drone/src/chain-abci/src/storage/mod.rs:171:27
FUZZER:     #18 0x55f747ca2741 in chain_abci::app::validate_tx::_$LT$impl$u20$chain_abci..app..app_init..ChainNodeApp$LT$T$GT$$GT$::handle_tx::hff5fd99739c8cc81 /drone/src/chain-abci/src/app/validate_tx.rs:81:29
FUZZER:     #19 0x55f747c9c2d3 in chain_abci::app::validate_tx::_$LT$impl$u20$chain_abci..app..app_init..ChainNodeApp$LT$T$GT$$GT$::validate_tx_req::hecb5521b1f051ff8 /drone/src/chain-abci/src/app/validate_tx.rs:105:29
FUZZER:     #20 0x55f747ccdaa8 in chain_abci::app::_$LT$impl$u20$abci..Application$u20$for$u20$chain_abci..app..app_init..ChainNodeApp$LT$T$GT$$GT$::check_tx::hec9ed565f5b25b25 /drone/src/chain-abci/src/app/mod.rs:59:14
FUZZER:     #21 0x55f747e1d41c in rust_fuzzer_test_input /drone/src/chain-abci/fuzz/fuzz_targets/abci_cycle.rs:205:24
FUZZER:     #22 0x55f747e66332 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::ha01d8331df2ab629 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/src/lib.rs:27:8
FUZZER:     #23 0x55f747ebbfb4 in std::panicking::try::do_call::he8fed3c089299fea /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:303:39
FUZZER:     #24 0x55f74d1fb6b6 in __rust_maybe_catch_panic /rustc/834bc5650acf7019a53b409db68986857822812c/src/libpanic_unwind/lib.rs:86:7
FUZZER:     #25 0x55f747ebb9a5 in std::panicking::try::h28bf4e88d6ce3579 /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panicking.rs:281:12
FUZZER:     #26 0x55f747e66adc in std::panic::catch_unwind::h77e9bbbc0ae05a8b /rustc/834bc5650acf7019a53b409db68986857822812c/src/libstd/panic.rs:394:13
FUZZER:     #27 0x55f747e65c79 in LLVMFuzzerTestOneInput /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/src/lib.rs:25:21
FUZZER:     #28 0x55f747e7fbf5 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerLoop.cpp:553
FUZZER:     #29 0x55f747e7f478 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerLoop.cpp:469
FUZZER:     #30 0x55f747e806e8 in fuzzer::Fuzzer::MutateAndTestOne() /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerLoop.cpp:696
FUZZER:     #31 0x55f747e812cf in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerLoop.cpp:831
FUZZER:     #32 0x55f747e6d6cb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerDriver.cpp:825
FUZZER:     #33 0x55f747e6597d in main /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.1/libfuzzer/FuzzerMain.cpp:19
FUZZER:     #34 0x7fe3a2c592e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
FUZZER:     #35 0x55f747acdab9 in _start (/app/fuzzer+0x1973ab9)
FUZZER: 
FUZZER: NOTE: libFuzzer has rudimentary signal handlers.
FUZZER:       Combine libFuzzer with AddressSanitizer or similar for better crash reports.
FUZZER: SUMMARY: libFuzzer: deadly signal
FUZZER: MS: 1 CopyPart-; base unit: ed77369df0fb9a0b7114fa42d81dfd5a355cd75e
FUZZER: artifact_prefix='./'; Test unit written to ./artifact
FUZZER: stat::number_of_executed_units: 14090
FUZZER: stat::average_exec_per_sec:     12
FUZZER: stat::new_units_added:          3
FUZZER: stat::slowest_unit_time_sec:    0
FUZZER: stat::peak_rss_mb:              479
2020/03/13 16:30:37 process finished with error = exit status 76
2020/03/13 16:30:37 Exit Status: 76
2020/03/13 16:30:38 uploading crash...

```

More details can be found [here](https://app.fuzzit.dev/orgs/crypto-com-gh/targets/abci-cycle/co6k5K0JWH9z2BHuEbYf)

Cheers,
Fuzzit Bot

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Check payload transaction type in mock enclave.

### CODE REVIEW

File: chain-abci/src/enclave_bridge/mock.rs [hunk 1]
```diff
@@ -234,7 +234,10 @@ impl EnclaveProxy for MockClient {
                 // FIXME
                 let plain_tx = PlainTxAux::decode(&mut txpayload.as_slice());
                 match (tx, plain_tx) {
-                    (_, Ok(PlainTxAux::TransferTx(maintx, witness))) => {
+                    (
+                        TxEnclaveAux::TransferTx { .. },
```
Comment (leejw51crypto) [inline chain-abci/src/enclave_bridge/mock.rs]: how this fix crashes?

Comment (yihuang) [reply chain-abci/src/enclave_bridge/mock.rs]: The crash happen when wrapper tx type and payload tx type don't match, so after we fix the pattern match like this, that problematic case will go to the default branch, which will return an error rather than crash.
