### PR TITLE
Problem:(fix #1004) client doesn't validate transactions it generates

### LINKED ISSUE #1004: Problem: client doesn't validate transactions it generates
add some context specific information in the error message
for example)
if incoins < total_outsum.unwrap() {
        let gap= total_outsum - incoins;
        let info=format!("more {} coin is necessary for fee in check_input_output_sums ", gap);
        return Err(Error::InputOutputDoNotMatch, gap);
}

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution: 
* Add fee check for transfer tx on client-side
 * check the staking address is jailed or not for the `deposit_bonded_stake` tx

### CODE REVIEW

File: client-network/src/network_ops/default_network_ops_client.rs [hunk 1]
```diff
@@ -166,6 +166,15 @@ where
             .iter()
             .map(|(input, _)| input.clone())
             .collect::<Vec<_>>();
+
+        let staked_state = self.get_staked_state(&to_address)?;
```
Comment (yihuang) [inline client-network/src/network_ops/default_network_ops_client.rs]: I think `get_staked_state` return error if address not exists on chain, but should be ok to be the to_address of deposit tx.

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs [hunk 2]
```diff
@@ -356,14 +356,25 @@ where
...
                 ErrorKind::VerifyError,
                 "Output amount exceed input amount",
             ));
         }
 
+        // check fee
+        let fee_in_tx = (input_value - output_value)
+            .chain(|| (ErrorKind::VerifyError, "Invalid amount of output or input"))?;
+        let fee_expect = self.estimate_fee()?;
+        if fee_in_tx < fee_expect {
```
Comment (yihuang) [inline client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: How about just single check: `input_value < output_value + min_fee`?

File: client-network/src/network_ops/default_network_ops_client.rs (hunk 1 above)
Comment (tomtau) [reply client-network/src/network_ops/default_network_ops_client.rs]: For withdraw, it's ok.
For deposit, it could be the case that this staked state wasn't created in genesis and this is the first transaction

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs [hunk 3]
```diff
@@ -356,14 +356,25 @@ where
...
         if input_value < output_value {
             return Err(Error::new(
                 ErrorKind::VerifyError,
                 "Output amount exceed input amount",
             ));
         }
 
+        // check fee
+        let fee_in_tx = (input_value - output_value)
+            .chain(|| (ErrorKind::VerifyError, "Invalid amount of output or input"))?;
```
Comment (leejw51crypto) [inline client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: how about
insufficient amount ,
because intput, output can be difficult for users

File: client-network/src/network_ops/default_network_ops_client.rs (hunk 1 above)
Comment (linfeng-crypto) [reply client-network/src/network_ops/default_network_ops_client.rs]: When deposit, if the staking address belongs to the wallet and `staked_state` does not exist, we let it go so that the user can be a validator. In other cases, if the staking address not exists, we can prevent a user's loss.

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs (hunk 3 above)
Comment (linfeng-crypto) [reply client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: I'll fix it.

File: client-network/src/network_ops/default_network_ops_client.rs (hunk 1 above)
Comment (yihuang) [reply client-network/src/network_ops/default_network_ops_client.rs]: > When deposit, if the staking address belongs to the wallet and `staked_state` does not exist, we let it go so that the user can be a validator. In other cases, if the staking address not exists, we can prevent a user's loss.

I think this function is about deposit tx, so it's problematic to return error on non-exist staking address.

Comment (tomtau) [reply client-network/src/network_ops/default_network_ops_client.rs]: >  In other cases, if the staking address not exists, we can prevent a user's loss.

it may be the case that it's really what you want to do -- e.g. @lezzokafka frequently deposits to addresses that are not managed by his wallet to distribute testnet tokens .

so rather than preventing it, it may just have an extra confirmation step

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs [hunk 4]
```diff
@@ -1057,11 +1066,11 @@ mod raw_transfer_transaction_builder_tests {
 
         builder.add_input((
             TxoPointer::new(random(), 0),
-            TxOut::new(transfer_addr.clone(), Coin::new(100).unwrap()),
+            TxOut::new(transfer_addr.clone(), Coin::new(500).unwrap()),
         ));
         builder.add_input((
             TxoPointer::new(random(), 0),
-            TxOut::new(transfer_addr, Coin::new(200).unwrap()),
+            TxOut::new(transfer_addr, Coin::new(500).unwrap()),
```
Comment (tomtau) [inline client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: why are the amount changes needed in tests?

Comment (tomtau) [reply client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: the fee was incorrect?

File: client-network/src/network_ops/default_network_ops_client.rs [hunk 5]
```diff
@@ -162,10 +162,23 @@ where
         to_address: StakedStateAddress,
         attributes: StakedStateOpAttributes,
     ) -> Result<(TxAux, TransactionPending)> {
+        // if the to_address belongs to current wallet, we do not check the state
+        let staking_addresses = self.wallet_client.staking_addresses(name, enckey)?;
+        if !staking_addresses.contains(&to_address) {
+            let staked_state = self.get_staked_state(&to_address)?;
+            verify_unjailed(&staked_state).map_err(|e| {
```
Comment (leejw51crypto) [inline client-network/src/network_ops/default_network_ops_client.rs]: how about using ".chain"?

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs [hunk 6]
```diff
@@ -356,14 +357,22 @@ where
...
 
-        // TODO: Include fee in calculation?
         if input_value < output_value {
+            return Err(Error::new(ErrorKind::VerifyError, "Insufficient balance"));
+        }
+        Ok(())
+    }
+
+    fn verify_fee(&self) -> Result<()> {
+        let fee_expect = self.estimate_fee()?;
```
Comment (leejw51crypto) [inline client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: how about "fee_expected"?

File: client-core/src/transaction_builder/raw_transfer_transaction_builder.rs (hunk 4 above)
Comment (linfeng-crypto) [reply client-core/src/transaction_builder/raw_transfer_transaction_builder.rs]: the old one inputs value equals to outputs value,  after I add fee check, some tests will fail.
