### PR TITLE
Problem (Fix #805): fixed package is not reviewed

### LINKED ISSUE #805: Problem: two fixed point arithmetic implementations
There's a custom fixed point arithmetic implementation that originally evolved from fee calculation that's used in most places.
Then there's a fixed point calculation for reward emission based on non-stable `fixed` crate.
As reward emission is a part of consensus, bugs or changes in `fixed` would have a critical impact... it'll be desirable to vendor-in, check and verify the needed portions of `fixed`

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Review and vendor-in related code into chain-core and document them.

### CODE REVIEW

File: chain-core/src/fixed/div.rs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+fn unnormalize(num: u128, zeros: u32) -> u128 {
+    num >> zeros
+}
+
+#[inline]
+fn div_half(num: &mut u128, d: u128, next_half: u128) -> u128 {
+    let (dh, dl) = hi_lo(d);
+    let (mut q, rr) = (*num / dh, *num % dh);
+    let m = q * dl;
+    *num = up_lo(rr, next_half);
```
Comment (yihuang) [inline chain-core/src/fixed/div.rs:96]: This part of code, I don't understand the math behind it.
I think it an approximation, to compute `num / (dh * 2^64 + dl)` based on `num / dh * 2^64 + ?`, an approximation `X`?

File: chain-core/src/fixed/div.rs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+    #[inline]
+    fn div(self: Fixed, other: Fixed) -> Fixed {
+        let (ans, overflow) = div_overflow(self.0, other.0, FRAC_NBITS);
+        debug_assert!(!overflow, "overflow");
+        Fixed(ans)
+    }
+}
+
+#[inline]
+fn div_overflow(lhs: i128, rhs: i128, frac_nbits: u32) -> (i128, bool) {
```
Comment (devashishdxt) [inline chain-core/src/fixed/div.rs:17]: Isn't `frac_nbits` a constant in our code?

File: chain-core/src/fixed/div.rs [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+    let q1h = div_half(&mut r, d, n1_hi);
+    let q1l = div_half(&mut r, d, n1_lo);
+    let (n0_hi, n0_lo) = hi_lo(n0);
+    let q0h = div_half(&mut r, d, n0_hi);
+    let q0l = div_half(&mut r, d, n0_lo);
+    ((up_lo(q1h, q1l), up_lo(q0h, q0l)), unnormalize(r, zeros))
+}
+
+#[inline]
+fn neg_abs2(num: (i128, u128)) -> (bool, (u128, u128)) {
```
Comment (devashishdxt) [inline chain-core/src/fixed/div.rs:49]: Some documentation on what this function does?

File: chain-core/src/fixed/div.rs (hunk 1 above)
Comment (tomtau) [reply chain-core/src/fixed/div.rs:96]: @lezzokafka

File: chain-core/src/fixed/continued_fraction.rs [hunk 4]
```diff
@@ -70,27 +72,27 @@ pub fn log2(x: Fixed, y: Fixed) -> Fixed {
...
         exp2(-staking_, tau_)
     };
-    let n1 = log2(n0 * r0, Fixed::from_num(1000));
+    let n1 = log2(n0 * r0, Fixed::from(1000));
     let n2 = exp2(n1 * period, year);
-    let n3 = staking * (n2 - Fixed::from_num(1));
+    let n3 = staking * (n2 - Fixed::from(1));
     // drop fraction part, no wrap
-    let n4 = n3.checked_to_num::<u64>().unwrap();
+    let n4: u64 = n3.try_into().unwrap();
```
[the remark this answers is not in the document]
Comment (yihuang) [reply chain-core/src/fixed/continued_fraction.rs]: Done

File: chain-core/src/fixed/mod.rs [hunk 5]
```diff
@@ -0,0 +1,242 @@
...
+/// fixed point number
+#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
+pub struct Fixed(pub(crate) i128);
+
+macro_rules! impl_from_integers {
+    ($($ty:tt),*) => {
+        $(
+            impl From<$ty> for Fixed {
+                fn from(n: $ty) -> Fixed {
+                    Fixed((n as i128) << FRAC_NBITS)
```
[the remark this answers is not in the document]
Comment (yihuang) [reply chain-core/src/fixed/mod.rs:42]: Removed not used implementations, may also help with unit test coverage.

File: chain-core/src/fixed/div.rs (hunk 2 above)
Comment (yihuang) [reply chain-core/src/fixed/div.rs:32]: Yes, but I think still good to keep the helper functions generic?

File: chain-core/src/fixed/div.rs (hunk 3 above)
Comment (yihuang) [reply chain-core/src/fixed/div.rs:65]: Done

**Comment by yihuang** [comment]
> for the code that comes from fixed, it'll be good to acknowledge that in the respective file headers + in the NOTICE file: https://github.com/crypto-com/chain/blob/master/NOTICE

Added the licence in the respective files, added the item in NOTICE file.

File: chain-core/src/fixed/display.rs [hunk 6]
```diff
@@ -0,0 +1,445 @@
...
+// modify it under the terms of either
+//
+//   * the Apache License, Version 2.0 or
+//   * the MIT License
+//
+// at your option.
+//
+// You should have recieved copies of the Apache License and the MIT
+// License along with the library. If not, see
+// <https://www.apache.org/licenses/LICENSE-2.0> and
```
Comment (tomtau) [inline chain-core/src/fixed/display.rs:13]: https://github.com/crypto-com/chain/blob/master/client-core/src/hd_wallet/mod.rs#L3

I guess it the redistribution copyright can be licensed under the Apache;
if there were any modifications to the original, also add our modifications copyright to make the license information clear

File: chain-core/src/fixed/div.rs (hunk 2 above)
Comment (devashishdxt) [reply chain-core/src/fixed/div.rs:32]: Then, take `nbits` also as a parameter?

Comment (yihuang) [reply chain-core/src/fixed/div.rs:21]: > Then, take `nbits` also as a parameter?

These codes are just adapted from [fixed](https://gitlab.com/tspiteri/fixed) with minimal changes, so I kept the overall structures.

Comment (devashishdxt) [reply chain-core/src/fixed/div.rs:21]: Ok.

File: chain-core/src/fixed/display.rs (hunk 6 above)
Comment (yihuang) [reply chain-core/src/fixed/display.rs]: Done

File: chain-core/src/fixed/div.rs (hunk 2 above)
Comment (yihuang) [reply chain-core/src/fixed/div.rs]: I just made the changes, since it's only related to this single function, so it's small.

File: chain-core/src/fixed/div.rs (hunk 1 above)
Comment (lezzokafka) [reply chain-core/src/fixed/div.rs:102]: @yihuang This actually looks like long division to me, where you have the quotient and the remainder part?

Comment (yihuang) [reply chain-core/src/fixed/div.rs:102]: The q refers to quotient, which is first computed with hi, then adjusted with lo.

**Comment by yihuang** [comment]
> There are a few merge conflicts. Can you rebase with latest master?

Done
