### PR TITLE
Problem: (fix #1775)no option for keypackage in client-cli, join-tx g…

### LINKED ISSUE #1775: Problem: no option for keypackage in client-cli, join-tx generation
because, keypackage is not short, in terminal environment, copy & paste not working correctly sometimes.

so, in client-cli add option
--keypackage key.txt
if option is given, read the file  , otherwise, ask of the user like now.

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution: add keypackage option to in `client-cli transaction` command. 
the parsed keypackage  display looks like:

```
    versions:     0
    life time:    from 1970-01-01T08:00:00+08:00 to 2020-08-24T18:47:48+08:00
    cipher_suite: 2
    signature:    MEYCIQCMuyJiNsebUhSQRy0nB0X0YnEhfx7PGI06g4cCYji5DAIhAIVO51V1SgjWhzmndDzWcYhrr5yLxrrSa8kl00JabIE/
    init_key:     HPKEPublicKey BEubL2bwSBsqxFLfSPIK863RWoGMe1rTqPWs44BoYYI+8n1JB9NsWgyiBuPny09nLT6ARropYzJcRAWVUwk9enU=
    extensions:   ["AAEAAgEA", "AAIAAwIAAg==", "AAMAEAAAAAAAAAAAAAAAAF9DmtQ="]
    X501 pubkey:  BEubL2bwSBsqxFLfSPIK863RWoGMe1rTqPWs44BoYYI+8n1JB9NsWgyiBuPny09nLT6ARropYzJcRAWVUwk9enU=
    quote_body:
        version:  2
        sig_type: 0
        gid:      3013
        pce_svn:  10
        basename: nduGA44BSoQO61k2L84aNT6BCdFSbGAcfgolNw81d38=
    quote_report_body:
        isv_svn:     Dw8CBf+ABwAAAAAAAAAAAA==
        isv_prod_id: BwAAAAAAAAAfAAAAAAAAAA==
        cpu_svn:     0
        attrbutes:   0
        report_data: S5svZvBIGyrEUt9I8grzrdFagYx7WtOo9azjgGhhgj7yfUkH02xaDKIG4+fLT2ctPoBGuiljMlxEBZVTCT16dQ==
        measurement:
            mr_signer:  nUcVFLnBL48fWEM3GKiYxkmCfzOeMiA+9FZtzYov3HA=
            mr_enclave: mv/Prke4SOwsrxxJtLKDUx4cxCX5NYKzaAblKkPXjRo=
```

### CODE REVIEW

File: client-cli/src/command/transaction_command.rs [hunk 1]
```diff
@@ -1009,13 +1024,97 @@ fn ask_transfer_address() -> Result<ExtendedAddr> {
...
+    let life_time = keypackage
+        .payload
+        .find_extension::<LifeTimeExt>()
+        .chain(|| {
+            (
+                ErrorKind::IllegalInput,
+                "can not find extention from keypackage",
+            )
+        })?;
+    let extension_begin = Local.timestamp(life_time.not_before as i64, 0);
```
Comment (leejw51crypto) [inline client-cli/src/command/transaction_command.rs:1056]: add some comment that this is `local` time

Comment (leejw51crypto) [reply client-cli/src/command/transaction_command.rs:1056]: also genesis time is utc time, how about specify utc/local time together

Comment (linfeng-crypto) [reply client-cli/src/command/transaction_command.rs:1056]: the timezone will be included in the result,  like: `2020-06-23T10:17:55.177825+08:00`, UTC time is not friendly for humans.

File: client-cli/src/command/transaction_command.rs [hunk 2]
```diff
@@ -106,6 +108,15 @@ pub enum TransactionCommand {
             case_insensitive = true
         )]
         advanced: bool,
+        #[structopt(
+            name = "keypacakage file path",
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:112]:
```suggestion
            name = "keypackage file path",
```

File: client-cli/src/command/transaction_command.rs [hunk 3]
```diff
@@ -106,6 +108,15 @@ pub enum TransactionCommand {
...
+            long = "keypackage",
+            parse(from_os_str),
+            help = "file path of base64 encoded key package for node-join transaction",
+            case_insensitive = true
+        )]
+        // config_file: Option<String>,
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:118]:
```suggestion
```

File: client-cli/src/command/transaction_command.rs [hunk 4]
```diff
@@ -1009,13 +1024,97 @@ fn ask_transfer_address() -> Result<ExtendedAddr> {
...
+            base64::encode(&extension_entry)
+        })
+        .collect::<Vec<_>>();
+    let credential = base64::encode(&credential);
+    let l = credential.len();
+    let credential_info = if l > 64 {
+        format!("{}........{}", &credential[0..32], &credential[l - 32..])
+    } else {
+        credential
+    };
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:1046]: instead of displaying credential as base64, it may be better to parse the X509 in it + extract the quote and show some information from it -- you can use https://github.com/crypto-com/chain/blob/master/chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs#L127 for it.
I guess here, for display, it could either display the extracted details, or the potential detected error

File: client-cli/src/command/transaction_command.rs [hunk 5]
```diff
@@ -516,6 +529,7 @@ fn new_transaction<T: WalletClient, N: NetworkOpsClient>(
     name: &str,
     transaction_type: &TransactionType,
     advanced: bool,
+    keypacakge: Option<PathBuf>,
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:532]:
```suggestion
    keypackage: Option<PathBuf>,
```

File: client-cli/src/command/transaction_command.rs [hunk 6]
```diff
@@ -563,7 +577,7 @@ fn new_transaction<T: WalletClient, N: NetworkOpsClient>(
             wallet_client.broadcast_transaction(&tx_aux)?;
         }
         TransactionType::NodeJoin => {
-            let tx_aux = new_node_join_transaction(network_ops_client, name, &enckey)?;
+            let tx_aux = new_node_join_transaction(network_ops_client, name, &enckey, keypacakge)?;
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:580]:
```suggestion
            let tx_aux = new_node_join_transaction(network_ops_client, name, &enckey, keypackage)?;
```

File: client-cli/src/command/transaction_command.rs [hunk 7]
```diff
@@ -826,10 +840,11 @@ fn new_node_join_transaction<N: NetworkOpsClient>(
     network_ops_client: &N,
     name: &str,
     enckey: &SecKey,
+    keypacakge: Option<PathBuf>,
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:843]:
```suggestion
    keypackage: Option<PathBuf>,
```

File: client-cli/src/command/transaction_command.rs [hunk 8]
```diff
@@ -826,10 +840,11 @@ fn new_node_join_transaction<N: NetworkOpsClient>(
...
 ) -> Result<TxAux> {
     let attributes = StakedStateOpAttributes::new(get_network_id());
     let staking_account_address = ask_staking_address()?;
-    let node_metadata = ask_node_metadata()?;
+    let node_metadata = ask_node_metadata(keypacakge)?;
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:847]:
```suggestion
    let node_metadata = ask_node_metadata(keypackage)?;
```

File: client-cli/src/command/transaction_command.rs [hunk 9]
```diff
@@ -1009,13 +1024,97 @@ fn ask_transfer_address() -> Result<ExtendedAddr> {
...
+
+    let info = format!(
+        r#"get keypackage information:
+    versions:     {:?}
+    life time:    {}
+    cipher_suite: {}
+    signature:    {}
+    init_key:     HPKEPublicKey {}
+    credential:   {}
+    extenstions:  {:?}
```
Comment (tomtau) [inline client-cli/src/command/transaction_command.rs:1069]:
```suggestion
    extensions:  {:?}
```
