### PR TITLE
Problem:(fix #1649) no graceful close in client-cli after sync

### LINKED ISSUE #1649: Problem: no graceful close in client-cli after sync
E[2020-05-22|15:52:14.037] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:39560 err="websocket: close 1006 (abnormal closure): unexpected EOF"
E[2020-05-22|15:52:14.037] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:39572 err="websocket: close 1006 (abnormal closure): unexpected EOF"

before finishing sync, graceful close websocket,
also check with client-rpc, too

### PR DESCRIPTION
**Pull request by leejw51crypto**
- send `close` websocket message before shutting down websocket
- to fix two `EOF` errors per syncing

### CODE REVIEW

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs [hunk 1]
```diff
@@ -309,4 +322,31 @@ impl Client for SyncRpcClient {
...
+/// close websocket connection by sending CLOSE message
+pub fn close_connection(writer: Arc<Mutex<WebSocketWriter>>) -> Result<()> {
+    // close
+
+    let runtime = Runtime::new().chain(|| {
+        (
+            ErrorKind::InitializationError,
+            "Unable to start tokio runtime",
+        )
+    })?;
```
Comment (devashishdxt) [inline client-common/src/tendermint/rpc_client/sync_rpc_client.rs:340]: Why are you creating a new `Runtime` just to close the connection?

**Comment by leejw51crypto** [comment]
it's the same with calling stream.close
that api also sends CloseFrame, because stream is owned in async-rpc-client.
but i'll check Drop , too.

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs (hunk 1 above)
Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:340]: because `close` is actually `sending close message`, it's async , future.
so to run it, needed runtime.
sharing runtime with original is a little complex, so chose making a new tokio runtime to run the future

Comment (devashishdxt) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:340]: If you do it in `Drop` implementation of `SyncRpcClient`, you'll also have access to the main `Runtime`?

Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:340]: ok, i'll try to do it on Drop

**Comment by leejw51crypto** [comment]
ok, i'll rebase

Drop working fine,
i'm changing that, too.

**Comment by leejw51crypto** [comment]
i tried to use self.runtime,
but it should be mutable to use block_on,
so i created runtime

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs [hunk 2]
```diff
@@ -310,3 +316,27 @@ impl Client for SyncRpcClient {
             .collect()
     }
 }
+
+impl Drop for SyncRpcClient {
+    fn drop(&mut self) {
+        let sender = self.async_rpc_client.websocket_writer.clone();
+
+        let mut runtime = Runtime::new()
```
[the remark this answers is not in the document]
Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:324]: it's not allowed in Arc,
but i'll try again

[the remark this answers is not in the document]
Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs]: ooooh, it works
i submitted

File: client-cli/src/command.rs [hunk 3]
```diff
@@ -385,7 +385,9 @@ impl Command {
                 block_height_ensure,
             } => {
                 let tendermint_client = WebsocketRpcClient::new(&tendermint_url())?;
-                let tx_obfuscation = get_tx_query(tendermint_client.clone())?;
+                let tendermint_client_tx_query = WebsocketRpcClient::new(&tendermint_url())?;
```
Comment (yihuang) [inline client-cli/src/command.rs:388]: Why two connections?

**Comment by yihuang** [comment]
Just a side note, someone might merge this much simpler version of implementation(https://gist.github.com/yihuang/a512e18b5bc59953b05255ffcf4ddc44) ;D

**Comment by devashishdxt** [comment]
> Just a side note, shall we merge this much simpler version of implementation sometime (https://gist.github.com/yihuang/a512e18b5bc59953b05255ffcf4ddc44) ;D

I think `smol` is still very new and there is not much ecosystem around it. `tokio` runtime is used in most places, for example, it is also used in our explorer backend code so its very easy to integrate that with `client-*` crates. We can think of using `smol` when there are good frameworks on top of `smol`. `smol` is definitely very simple but it is also very new.

File: client-cli/src/command.rs (hunk 3 above)
Comment (leejw51crypto) [reply client-cli/src/command.rs:388]: if it cloned,  some disconnect message, occurs, 
i'll show it shortly

**Comment by tomtau** [comment]
bors try

**Comment by leejw51crypto** [comment]
i'll check

File: client-cli/src/command.rs (hunk 3 above)
Comment (leejw51crypto) [reply client-cli/src/command.rs]: remove two connections

**Comment by tomtau** [comment]
bors try

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs [hunk 4]
```diff
@@ -11,20 +11,29 @@ use tendermint::{lite, validator};
...
 /// Wraps asynchronous RPC client and executes it in tokio runtime
 #[derive(Clone)]
 pub struct SyncRpcClient {
-    runtime: Arc<Runtime>,
-    async_rpc_client: AsyncRpcClient,
+    runtime: Arc<Mutex<Runtime>>,
+    /// ASYNC RPC CLIENT
+    pub async_rpc_client: AsyncRpcClient,
+    /// graceful close on Drop
+    pub disconnect_on_drop: bool,
```
Comment (devashishdxt) [inline client-common/src/tendermint/rpc_client/sync_rpc_client.rs:36]: Why do we need a flag for this? Shouldn't this be the default behaviour?

Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:36]: RpcClient is cloned, without that, integration test breaks.
also don't to shutdown it gracefully for all cases

File: client-common/src/tendermint/rpc_client/sync_rpc_client.rs [hunk 5]
```diff
@@ -310,3 +320,20 @@ impl Client for SyncRpcClient {
             .collect()
     }
 }
+
+impl Drop for SyncRpcClient {
+    fn drop(&mut self) {
+        if self.disconnect_on_drop {
```
Comment (devashishdxt) [inline client-common/src/tendermint/rpc_client/sync_rpc_client.rs:326]: Instead of having a boolean flag, you can check following condition:
```
if Arc::strong_count(&self.runtime) == 1 {
    // Close connection
}
```

Comment (leejw51crypto) [reply client-common/src/tendermint/rpc_client/sync_rpc_client.rs:326]: ok, that's better solution.
i'll check it

**Comment by tomtau** [comment]
bors try
